# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata
from ...requests.web_data_balance import WebDataBalanceParams
from .get_account_balances_response_proxy import GetAccountBalancesResponseProxyParams


class GetAccountBalancesResponseParams(typing_extensions.TypedDict):
    web_data: typing_extensions.NotRequired[
        typing_extensions.Annotated[WebDataBalanceParams, FieldMetadata(alias="webData")]
    ]
    proxy: typing_extensions.NotRequired[GetAccountBalancesResponseProxyParams]
