# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...requests.rotating_proxy_balance import RotatingProxyBalanceParams
from .get_account_balances_response_proxy_static import GetAccountBalancesResponseProxyStaticParams


class GetAccountBalancesResponseProxyParams(typing_extensions.TypedDict):
    rotating: typing_extensions.NotRequired[typing.Optional[RotatingProxyBalanceParams]]
    static: typing_extensions.NotRequired[typing.Optional[GetAccountBalancesResponseProxyStaticParams]]
