# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .get_account_usage_response_proxy_rotating import GetAccountUsageResponseProxyRotatingParams


class GetAccountUsageResponseProxyParams(typing_extensions.TypedDict):
    rotating: typing_extensions.NotRequired[typing.Optional[GetAccountUsageResponseProxyRotatingParams]]
