# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata
from ...requests.rotating_proxy_traffic_usage import RotatingProxyTrafficUsageParams


class GetAccountUsageResponseProxyRotatingParams(typing_extensions.TypedDict):
    traffic: RotatingProxyTrafficUsageParams
    last_updated_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="lastUpdatedAt")]
