# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class GetAccountBalancesResponseProxyStaticParams(typing_extensions.TypedDict):
    active_ip_count: typing_extensions.Annotated[int, FieldMetadata(alias="activeIpCount")]
    pending_ip_count: typing_extensions.Annotated[int, FieldMetadata(alias="pendingIpCount")]
