# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata
from .get_account_usage_response_filters import GetAccountUsageResponseFiltersParams
from .get_account_usage_response_proxy import GetAccountUsageResponseProxyParams
from .get_account_usage_response_web_data import GetAccountUsageResponseWebDataParams


class GetAccountUsageResponseParams(typing_extensions.TypedDict):
    web_data: typing_extensions.NotRequired[
        typing_extensions.Annotated[GetAccountUsageResponseWebDataParams, FieldMetadata(alias="webData")]
    ]
    proxy: typing_extensions.NotRequired[GetAccountUsageResponseProxyParams]
    last_updated_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="lastUpdatedAt")]
    """
    Most recent usage timestamp across included products.
    """

    filters: GetAccountUsageResponseFiltersParams
