# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class FetchWebDataResponseParams(typing_extensions.TypedDict):
    html: str
    """
    HTML content returned by the target page.
    """

    source_url: typing_extensions.Annotated[str, FieldMetadata(alias="sourceUrl")]
    """
    Target URL that was fetched.
    """

    fetched_at: typing_extensions.Annotated[str, FieldMetadata(alias="fetchedAt")]
    """
    ISO 8601 timestamp when the fetch completed.
    """
