# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class GetWebDataUsageResponseFiltersParams(typing_extensions.TypedDict):
    from_: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="from")]]
    to: typing_extensions.NotRequired[str]
