# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata
from ...requests.web_data_request_usage import WebDataRequestUsageParams
from .get_web_data_usage_response_filters import GetWebDataUsageResponseFiltersParams


class GetWebDataUsageResponseParams(typing_extensions.TypedDict):
    requests: WebDataRequestUsageParams
    last_updated_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="lastUpdatedAt")]
    """
    Most recent Web Data API request timestamp for the filters.
    """

    filters: GetWebDataUsageResponseFiltersParams
