# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata
from ...requests.web_data_search_result import WebDataSearchResultParams


class SearchWebDataResponseParams(typing_extensions.TypedDict):
    request_id: typing_extensions.Annotated[str, FieldMetadata(alias="requestId")]
    """
    Unique identifier for this search request.
    """

    query: str
    """
    Normalized search query.
    """

    results: typing.Sequence[WebDataSearchResultParams]
    """
    Organic results in search ranking order.
    """
