# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class CheckProxyRequestConnectionStringParams(typing_extensions.TypedDict):
    connection_string: typing_extensions.Annotated[str, FieldMetadata(alias="connectionString")]
    """
    Proxy URL to check. Replace the example username and password with real proxy credentials.
    """
