# This file was auto-generated by Fern from our API Definition.

import typing

from .check_proxy_request_connection_string import CheckProxyRequestConnectionStringParams
from .check_proxy_request_host import CheckProxyRequestHostParams

CheckProxyRequestParams = typing.Union[CheckProxyRequestConnectionStringParams, CheckProxyRequestHostParams]
