# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class CheckProxyResponseLocationParams(typing_extensions.TypedDict):
    country_code: typing_extensions.Annotated[str, FieldMetadata(alias="countryCode")]
    country: str
    state: str
    city: str
