# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .check_proxy_response_location import CheckProxyResponseLocationParams


class CheckProxyResponseParams(typing_extensions.TypedDict):
    ip: str
    location: CheckProxyResponseLocationParams
