# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.check_proxy_request_host_protocol import CheckProxyRequestHostProtocol


class CheckProxyRequestHostParams(typing_extensions.TypedDict):
    host: str
    port: int
    username: str
    """
    Proxy username to check.
    """

    password: str
    """
    Proxy password to check.
    """

    protocol: typing_extensions.NotRequired[CheckProxyRequestHostProtocol]
