# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..requests.get_web_data_usage_request_from import GetWebDataUsageRequestFromParams
from ..requests.get_web_data_usage_request_to import GetWebDataUsageRequestToParams
from ..types.web_data_balance import WebDataBalance
from .raw_client import AsyncRawWebDataClient, RawWebDataClient
from .types.fetch_web_data_request_difficulty import FetchWebDataRequestDifficulty
from .types.fetch_web_data_response import FetchWebDataResponse
from .types.get_web_data_usage_response import GetWebDataUsageResponse
from .types.search_web_data_response import SearchWebDataResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebDataClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebDataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebDataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebDataClient
        """
        return self._raw_client

    def fetch_web_data(
        self,
        *,
        url: str,
        country_code: typing.Optional[str] = OMIT,
        city: typing.Optional[str] = OMIT,
        difficulty: typing.Optional[FetchWebDataRequestDifficulty] = OMIT,
        render_delay_ms: typing.Optional[int] = OMIT,
        cache_max_age_days: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FetchWebDataResponse:
        """
        Fetches a page and returns its rendered HTML. Explicit low, medium, or high difficulty makes one attempt; auto retries low, then medium, then high only after a failed attempt. The first successful attempt consumes one Web Data request. Failed fetches return structured v2 JSON errors with message "Failed to scrape the URL" and safe metadata only. Use this for page retrieval. Do not use it for usage reporting; use getWebDataUsage or getAccountUsage instead.

        Parameters
        ----------
        url : str
            Target page URL to fetch through Web Data.

        country_code : typing.Optional[str]
            2-letter country code for the request exit location.

        city : typing.Optional[str]
            City for the request exit location.

        difficulty : typing.Optional[FetchWebDataRequestDifficulty]
            Access difficulty pool. low, medium, and high make one attempt. auto retries low, then medium, then high after a failed attempt. Omit this field to make one attempt at the default difficulty.

        render_delay_ms : typing.Optional[int]
            Delay before rendered HTML is returned, in milliseconds.

        cache_max_age_days : typing.Optional[int]
            Maximum age of cached content in days, from 0 to 1.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FetchWebDataResponse
            Fetched page HTML.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.web_data.fetch_web_data(
            url="https://example.com",
        )
        """
        _response = self._raw_client.fetch_web_data(
            url=url,
            country_code=country_code,
            city=city,
            difficulty=difficulty,
            render_delay_ms=render_delay_ms,
            cache_max_age_days=cache_max_age_days,
            request_options=request_options,
        )
        return _response.data

    def search_web_data(
        self,
        *,
        query: str,
        num_results: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchWebDataResponse:
        """
        Searches the public web and returns lightweight organic results in ranking order. One successful search consumes one Web Data request. Use this to discover relevant pages; use fetchWebData when you already have a URL and need its HTML. AI overviews, related questions, and location controls are not included.

        Parameters
        ----------
        query : str
            Search query. Whitespace is trimmed before searching.

        num_results : typing.Optional[int]
            Maximum number of organic results to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchWebDataResponse
            Normalized organic search results.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.web_data.search_web_data(
            query="browser automation",
        )
        """
        _response = self._raw_client.search_web_data(
            query=query, num_results=num_results, request_options=request_options
        )
        return _response.data

    def get_web_data_balance(self, *, request_options: typing.Optional[RequestOptions] = None) -> WebDataBalance:
        """
        Returns the authenticated account balance for Web Data requests only. Use getAccountBalances for an account-level rollup across products.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebDataBalance
            Web Data request balance.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.web_data.get_web_data_balance()
        """
        _response = self._raw_client.get_web_data_balance(request_options=request_options)
        return _response.data

    def get_web_data_usage(
        self,
        *,
        from_: typing.Optional[GetWebDataUsageRequestFromParams] = None,
        to: typing.Optional[GetWebDataUsageRequestToParams] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetWebDataUsageResponse:
        """
        Returns Web Data API usage for the authenticated account as UTC period rollups: yesterday, last7Days, and last30Days. If from or to is supplied, the response also includes requestedRange. Use this for Web Data-only reporting.

        Parameters
        ----------
        from_ : typing.Optional[GetWebDataUsageRequestFromParams]
            Start date or datetime in RFC 3339 format.

        to : typing.Optional[GetWebDataUsageRequestToParams]
            End date or datetime in RFC 3339 format.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebDataUsageResponse
            Web Data request usage.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.web_data.get_web_data_usage()
        """
        _response = self._raw_client.get_web_data_usage(from_=from_, to=to, request_options=request_options)
        return _response.data


class AsyncWebDataClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebDataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebDataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebDataClient
        """
        return self._raw_client

    async def fetch_web_data(
        self,
        *,
        url: str,
        country_code: typing.Optional[str] = OMIT,
        city: typing.Optional[str] = OMIT,
        difficulty: typing.Optional[FetchWebDataRequestDifficulty] = OMIT,
        render_delay_ms: typing.Optional[int] = OMIT,
        cache_max_age_days: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FetchWebDataResponse:
        """
        Fetches a page and returns its rendered HTML. Explicit low, medium, or high difficulty makes one attempt; auto retries low, then medium, then high only after a failed attempt. The first successful attempt consumes one Web Data request. Failed fetches return structured v2 JSON errors with message "Failed to scrape the URL" and safe metadata only. Use this for page retrieval. Do not use it for usage reporting; use getWebDataUsage or getAccountUsage instead.

        Parameters
        ----------
        url : str
            Target page URL to fetch through Web Data.

        country_code : typing.Optional[str]
            2-letter country code for the request exit location.

        city : typing.Optional[str]
            City for the request exit location.

        difficulty : typing.Optional[FetchWebDataRequestDifficulty]
            Access difficulty pool. low, medium, and high make one attempt. auto retries low, then medium, then high after a failed attempt. Omit this field to make one attempt at the default difficulty.

        render_delay_ms : typing.Optional[int]
            Delay before rendered HTML is returned, in milliseconds.

        cache_max_age_days : typing.Optional[int]
            Maximum age of cached content in days, from 0 to 1.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FetchWebDataResponse
            Fetched page HTML.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.web_data.fetch_web_data(
                url="https://example.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.fetch_web_data(
            url=url,
            country_code=country_code,
            city=city,
            difficulty=difficulty,
            render_delay_ms=render_delay_ms,
            cache_max_age_days=cache_max_age_days,
            request_options=request_options,
        )
        return _response.data

    async def search_web_data(
        self,
        *,
        query: str,
        num_results: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchWebDataResponse:
        """
        Searches the public web and returns lightweight organic results in ranking order. One successful search consumes one Web Data request. Use this to discover relevant pages; use fetchWebData when you already have a URL and need its HTML. AI overviews, related questions, and location controls are not included.

        Parameters
        ----------
        query : str
            Search query. Whitespace is trimmed before searching.

        num_results : typing.Optional[int]
            Maximum number of organic results to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchWebDataResponse
            Normalized organic search results.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.web_data.search_web_data(
                query="browser automation",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_web_data(
            query=query, num_results=num_results, request_options=request_options
        )
        return _response.data

    async def get_web_data_balance(self, *, request_options: typing.Optional[RequestOptions] = None) -> WebDataBalance:
        """
        Returns the authenticated account balance for Web Data requests only. Use getAccountBalances for an account-level rollup across products.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebDataBalance
            Web Data request balance.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.web_data.get_web_data_balance()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_web_data_balance(request_options=request_options)
        return _response.data

    async def get_web_data_usage(
        self,
        *,
        from_: typing.Optional[GetWebDataUsageRequestFromParams] = None,
        to: typing.Optional[GetWebDataUsageRequestToParams] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetWebDataUsageResponse:
        """
        Returns Web Data API usage for the authenticated account as UTC period rollups: yesterday, last7Days, and last30Days. If from or to is supplied, the response also includes requestedRange. Use this for Web Data-only reporting.

        Parameters
        ----------
        from_ : typing.Optional[GetWebDataUsageRequestFromParams]
            Start date or datetime in RFC 3339 format.

        to : typing.Optional[GetWebDataUsageRequestToParams]
            End date or datetime in RFC 3339 format.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebDataUsageResponse
            Web Data request usage.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.web_data.get_web_data_usage()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_web_data_usage(from_=from_, to=to, request_options=request_options)
        return _response.data
