# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_gateway_error import BadGatewayError
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.payment_required_error import PaymentRequiredError
from ..errors.unauthorized_error import UnauthorizedError
from ..requests.get_web_data_usage_request_from import GetWebDataUsageRequestFromParams
from ..requests.get_web_data_usage_request_to import GetWebDataUsageRequestToParams
from ..types.api_error_body import ApiErrorBody
from ..types.web_data_balance import WebDataBalance
from .types.fetch_web_data_request_difficulty import FetchWebDataRequestDifficulty
from .types.fetch_web_data_response import FetchWebDataResponse
from .types.get_web_data_usage_response import GetWebDataUsageResponse
from .types.search_web_data_response import SearchWebDataResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawWebDataClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def fetch_web_data(
        self,
        *,
        url: str,
        country_code: typing.Optional[str] = OMIT,
        city: typing.Optional[str] = OMIT,
        difficulty: typing.Optional[FetchWebDataRequestDifficulty] = OMIT,
        render_delay_ms: typing.Optional[int] = OMIT,
        cache_max_age_days: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[FetchWebDataResponse]:
        """
        Fetches a page and returns its rendered HTML. Explicit low, medium, or high difficulty makes one attempt; auto retries low, then medium, then high only after a failed attempt. The first successful attempt consumes one Web Data request. Failed fetches return structured v2 JSON errors with message "Failed to scrape the URL" and safe metadata only. Use this for page retrieval. Do not use it for usage reporting; use getWebDataUsage or getAccountUsage instead.

        Parameters
        ----------
        url : str
            Target page URL to fetch through Web Data.

        country_code : typing.Optional[str]
            2-letter country code for the request exit location.

        city : typing.Optional[str]
            City for the request exit location.

        difficulty : typing.Optional[FetchWebDataRequestDifficulty]
            Access difficulty pool. low, medium, and high make one attempt. auto retries low, then medium, then high after a failed attempt. Omit this field to make one attempt at the default difficulty.

        render_delay_ms : typing.Optional[int]
            Delay before rendered HTML is returned, in milliseconds.

        cache_max_age_days : typing.Optional[int]
            Maximum age of cached content in days, from 0 to 1.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[FetchWebDataResponse]
            Fetched page HTML.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/web-data/fetch",
            method="POST",
            json={
                "url": url,
                "countryCode": country_code,
                "city": city,
                "difficulty": difficulty,
                "renderDelayMs": render_delay_ms,
                "cacheMaxAgeDays": cache_max_age_days,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    FetchWebDataResponse,
                    parse_obj_as(
                        type_=FetchWebDataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def search_web_data(
        self,
        *,
        query: str,
        num_results: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SearchWebDataResponse]:
        """
        Searches the public web and returns lightweight organic results in ranking order. One successful search consumes one Web Data request. Use this to discover relevant pages; use fetchWebData when you already have a URL and need its HTML. AI overviews, related questions, and location controls are not included.

        Parameters
        ----------
        query : str
            Search query. Whitespace is trimmed before searching.

        num_results : typing.Optional[int]
            Maximum number of organic results to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SearchWebDataResponse]
            Normalized organic search results.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/web-data/search",
            method="POST",
            json={
                "query": query,
                "numResults": num_results,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchWebDataResponse,
                    parse_obj_as(
                        type_=SearchWebDataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_web_data_balance(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WebDataBalance]:
        """
        Returns the authenticated account balance for Web Data requests only. Use getAccountBalances for an account-level rollup across products.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WebDataBalance]
            Web Data request balance.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/web-data/balance",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebDataBalance,
                    parse_obj_as(
                        type_=WebDataBalance,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_web_data_usage(
        self,
        *,
        from_: typing.Optional[GetWebDataUsageRequestFromParams] = None,
        to: typing.Optional[GetWebDataUsageRequestToParams] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetWebDataUsageResponse]:
        """
        Returns Web Data API usage for the authenticated account as UTC period rollups: yesterday, last7Days, and last30Days. If from or to is supplied, the response also includes requestedRange. Use this for Web Data-only reporting.

        Parameters
        ----------
        from_ : typing.Optional[GetWebDataUsageRequestFromParams]
            Start date or datetime in RFC 3339 format.

        to : typing.Optional[GetWebDataUsageRequestToParams]
            End date or datetime in RFC 3339 format.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetWebDataUsageResponse]
            Web Data request usage.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/web-data/usage",
            method="GET",
            params={
                "from": convert_and_respect_annotation_metadata(
                    object_=convert_and_respect_annotation_metadata(
                        object_=from_, annotation=GetWebDataUsageRequestFromParams, direction="write"
                    ),
                    annotation=GetWebDataUsageRequestFromParams,
                    direction="write",
                ),
                "to": convert_and_respect_annotation_metadata(
                    object_=convert_and_respect_annotation_metadata(
                        object_=to, annotation=GetWebDataUsageRequestToParams, direction="write"
                    ),
                    annotation=GetWebDataUsageRequestToParams,
                    direction="write",
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWebDataUsageResponse,
                    parse_obj_as(
                        type_=GetWebDataUsageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWebDataClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def fetch_web_data(
        self,
        *,
        url: str,
        country_code: typing.Optional[str] = OMIT,
        city: typing.Optional[str] = OMIT,
        difficulty: typing.Optional[FetchWebDataRequestDifficulty] = OMIT,
        render_delay_ms: typing.Optional[int] = OMIT,
        cache_max_age_days: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[FetchWebDataResponse]:
        """
        Fetches a page and returns its rendered HTML. Explicit low, medium, or high difficulty makes one attempt; auto retries low, then medium, then high only after a failed attempt. The first successful attempt consumes one Web Data request. Failed fetches return structured v2 JSON errors with message "Failed to scrape the URL" and safe metadata only. Use this for page retrieval. Do not use it for usage reporting; use getWebDataUsage or getAccountUsage instead.

        Parameters
        ----------
        url : str
            Target page URL to fetch through Web Data.

        country_code : typing.Optional[str]
            2-letter country code for the request exit location.

        city : typing.Optional[str]
            City for the request exit location.

        difficulty : typing.Optional[FetchWebDataRequestDifficulty]
            Access difficulty pool. low, medium, and high make one attempt. auto retries low, then medium, then high after a failed attempt. Omit this field to make one attempt at the default difficulty.

        render_delay_ms : typing.Optional[int]
            Delay before rendered HTML is returned, in milliseconds.

        cache_max_age_days : typing.Optional[int]
            Maximum age of cached content in days, from 0 to 1.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[FetchWebDataResponse]
            Fetched page HTML.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/web-data/fetch",
            method="POST",
            json={
                "url": url,
                "countryCode": country_code,
                "city": city,
                "difficulty": difficulty,
                "renderDelayMs": render_delay_ms,
                "cacheMaxAgeDays": cache_max_age_days,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    FetchWebDataResponse,
                    parse_obj_as(
                        type_=FetchWebDataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def search_web_data(
        self,
        *,
        query: str,
        num_results: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SearchWebDataResponse]:
        """
        Searches the public web and returns lightweight organic results in ranking order. One successful search consumes one Web Data request. Use this to discover relevant pages; use fetchWebData when you already have a URL and need its HTML. AI overviews, related questions, and location controls are not included.

        Parameters
        ----------
        query : str
            Search query. Whitespace is trimmed before searching.

        num_results : typing.Optional[int]
            Maximum number of organic results to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SearchWebDataResponse]
            Normalized organic search results.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/web-data/search",
            method="POST",
            json={
                "query": query,
                "numResults": num_results,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchWebDataResponse,
                    parse_obj_as(
                        type_=SearchWebDataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_web_data_balance(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WebDataBalance]:
        """
        Returns the authenticated account balance for Web Data requests only. Use getAccountBalances for an account-level rollup across products.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WebDataBalance]
            Web Data request balance.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/web-data/balance",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebDataBalance,
                    parse_obj_as(
                        type_=WebDataBalance,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_web_data_usage(
        self,
        *,
        from_: typing.Optional[GetWebDataUsageRequestFromParams] = None,
        to: typing.Optional[GetWebDataUsageRequestToParams] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetWebDataUsageResponse]:
        """
        Returns Web Data API usage for the authenticated account as UTC period rollups: yesterday, last7Days, and last30Days. If from or to is supplied, the response also includes requestedRange. Use this for Web Data-only reporting.

        Parameters
        ----------
        from_ : typing.Optional[GetWebDataUsageRequestFromParams]
            Start date or datetime in RFC 3339 format.

        to : typing.Optional[GetWebDataUsageRequestToParams]
            End date or datetime in RFC 3339 format.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetWebDataUsageResponse]
            Web Data request usage.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/web-data/usage",
            method="GET",
            params={
                "from": convert_and_respect_annotation_metadata(
                    object_=convert_and_respect_annotation_metadata(
                        object_=from_, annotation=GetWebDataUsageRequestFromParams, direction="write"
                    ),
                    annotation=GetWebDataUsageRequestFromParams,
                    direction="write",
                ),
                "to": convert_and_respect_annotation_metadata(
                    object_=convert_and_respect_annotation_metadata(
                        object_=to, annotation=GetWebDataUsageRequestToParams, direction="write"
                    ),
                    annotation=GetWebDataUsageRequestToParams,
                    direction="write",
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetWebDataUsageResponse,
                    parse_obj_as(
                        type_=GetWebDataUsageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
