# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_account_usage_response_filters import GetAccountUsageResponseFilters
from .get_account_usage_response_proxy import GetAccountUsageResponseProxy
from .get_account_usage_response_web_data import GetAccountUsageResponseWebData


class GetAccountUsageResponse(UniversalBaseModel):
    web_data: typing_extensions.Annotated[
        typing.Optional[GetAccountUsageResponseWebData], FieldMetadata(alias="webData"), pydantic.Field(alias="webData")
    ] = None
    proxy: typing.Optional[GetAccountUsageResponseProxy] = None
    last_updated_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastUpdatedAt"),
        pydantic.Field(alias="lastUpdatedAt", description="Most recent usage timestamp across included products."),
    ] = None
    """
    Most recent usage timestamp across included products.
    """

    filters: GetAccountUsageResponseFilters

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
