# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.rotating_proxy_balance import RotatingProxyBalance
from .get_account_balances_response_proxy_static import GetAccountBalancesResponseProxyStatic


class GetAccountBalancesResponseProxy(UniversalBaseModel):
    rotating: typing.Optional[RotatingProxyBalance] = None
    static: typing.Optional[GetAccountBalancesResponseProxyStatic] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
