# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_account_usage_response_filters_proxy_type import GetAccountUsageResponseFiltersProxyType


class GetAccountUsageResponseFilters(UniversalBaseModel):
    from_: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="from"), pydantic.Field(alias="from")
    ] = None
    to: typing.Optional[str] = None
    subuser_id: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="subuserId"), pydantic.Field(alias="subuserId")
    ] = None
    proxy_type: typing_extensions.Annotated[
        typing.Optional[GetAccountUsageResponseFiltersProxyType],
        FieldMetadata(alias="proxyType"),
        pydantic.Field(alias="proxyType", description="Proxy type"),
    ] = None
    """
    Proxy type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
