# This file was auto-generated by Fern from our API Definition.

import typing

GetAccountBalancesRequestProduct = typing.Union[
    typing.Literal["web-data", "proxy-rotating", "proxy-static"], typing.Any
]
