# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.web_data_balance import WebDataBalance
from .get_account_balances_response_proxy import GetAccountBalancesResponseProxy


class GetAccountBalancesResponse(UniversalBaseModel):
    web_data: typing_extensions.Annotated[
        typing.Optional[WebDataBalance], FieldMetadata(alias="webData"), pydantic.Field(alias="webData")
    ] = None
    proxy: typing.Optional[GetAccountBalancesResponseProxy] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
