# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..requests.get_account_usage_request_from import GetAccountUsageRequestFromParams
from ..requests.get_account_usage_request_to import GetAccountUsageRequestToParams
from .raw_client import AsyncRawAccountClient, RawAccountClient
from .types.get_account_balances_request_product import GetAccountBalancesRequestProduct
from .types.get_account_balances_response import GetAccountBalancesResponse
from .types.get_account_usage_request_product import GetAccountUsageRequestProduct
from .types.get_account_usage_request_proxy_type import GetAccountUsageRequestProxyType
from .types.get_account_usage_response import GetAccountUsageResponse


class AccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAccountClient
        """
        return self._raw_client

    def get_account_balances(
        self,
        *,
        product: typing.Optional[GetAccountBalancesRequestProduct] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAccountBalancesResponse:
        """
        Returns account-level balance summaries across available products. Use product-scoped balance endpoints when a page only needs one product.

        Parameters
        ----------
        product : typing.Optional[GetAccountBalancesRequestProduct]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAccountBalancesResponse
            Account balance summaries.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.account.get_account_balances()
        """
        _response = self._raw_client.get_account_balances(product=product, request_options=request_options)
        return _response.data

    def get_account_usage(
        self,
        *,
        product: typing.Optional[GetAccountUsageRequestProduct] = None,
        from_: typing.Optional[GetAccountUsageRequestFromParams] = None,
        to: typing.Optional[GetAccountUsageRequestToParams] = None,
        subuser_id: typing.Optional[int] = None,
        proxy_type: typing.Optional[GetAccountUsageRequestProxyType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAccountUsageResponse:
        """
        Returns account-level usage across products with usage reporting as UTC period rollups. If from or to is supplied, product usage also includes requestedRange. Use subuserId from /v2/proxy/rotating/subusers to narrow rotating proxy usage; it does not apply to Web Data. Rotating proxy rollups report total traffic with txBytes and rxBytes set to null. Static proxies are inventory-only and are not included in usage responses.

        Parameters
        ----------
        product : typing.Optional[GetAccountUsageRequestProduct]

        from_ : typing.Optional[GetAccountUsageRequestFromParams]
            Date or datetime in RFC 3339 format

        to : typing.Optional[GetAccountUsageRequestToParams]
            Date or datetime in RFC 3339 format

        subuser_id : typing.Optional[int]
            Rotating proxy subuser ID from GET /v2/proxy/rotating/subusers. Omit to include all account subusers.

        proxy_type : typing.Optional[GetAccountUsageRequestProxyType]
            Rotating proxy type. Applies to rotating proxy usage.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAccountUsageResponse
            Account usage across available products.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.account.get_account_usage(
            subuser_id=123,
        )
        """
        _response = self._raw_client.get_account_usage(
            product=product,
            from_=from_,
            to=to,
            subuser_id=subuser_id,
            proxy_type=proxy_type,
            request_options=request_options,
        )
        return _response.data


class AsyncAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAccountClient
        """
        return self._raw_client

    async def get_account_balances(
        self,
        *,
        product: typing.Optional[GetAccountBalancesRequestProduct] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAccountBalancesResponse:
        """
        Returns account-level balance summaries across available products. Use product-scoped balance endpoints when a page only needs one product.

        Parameters
        ----------
        product : typing.Optional[GetAccountBalancesRequestProduct]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAccountBalancesResponse
            Account balance summaries.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.account.get_account_balances()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_account_balances(product=product, request_options=request_options)
        return _response.data

    async def get_account_usage(
        self,
        *,
        product: typing.Optional[GetAccountUsageRequestProduct] = None,
        from_: typing.Optional[GetAccountUsageRequestFromParams] = None,
        to: typing.Optional[GetAccountUsageRequestToParams] = None,
        subuser_id: typing.Optional[int] = None,
        proxy_type: typing.Optional[GetAccountUsageRequestProxyType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAccountUsageResponse:
        """
        Returns account-level usage across products with usage reporting as UTC period rollups. If from or to is supplied, product usage also includes requestedRange. Use subuserId from /v2/proxy/rotating/subusers to narrow rotating proxy usage; it does not apply to Web Data. Rotating proxy rollups report total traffic with txBytes and rxBytes set to null. Static proxies are inventory-only and are not included in usage responses.

        Parameters
        ----------
        product : typing.Optional[GetAccountUsageRequestProduct]

        from_ : typing.Optional[GetAccountUsageRequestFromParams]
            Date or datetime in RFC 3339 format

        to : typing.Optional[GetAccountUsageRequestToParams]
            Date or datetime in RFC 3339 format

        subuser_id : typing.Optional[int]
            Rotating proxy subuser ID from GET /v2/proxy/rotating/subusers. Omit to include all account subusers.

        proxy_type : typing.Optional[GetAccountUsageRequestProxyType]
            Rotating proxy type. Applies to rotating proxy usage.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAccountUsageResponse
            Account usage across available products.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.account.get_account_usage(
                subuser_id=123,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_account_usage(
            product=product,
            from_=from_,
            to=to,
            subuser_id=subuser_id,
            proxy_type=proxy_type,
            request_options=request_options,
        )
        return _response.data
