# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_gateway_error import BadGatewayError
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.payment_required_error import PaymentRequiredError
from ..errors.unauthorized_error import UnauthorizedError
from ..requests.get_account_usage_request_from import GetAccountUsageRequestFromParams
from ..requests.get_account_usage_request_to import GetAccountUsageRequestToParams
from ..types.api_error_body import ApiErrorBody
from .types.get_account_balances_request_product import GetAccountBalancesRequestProduct
from .types.get_account_balances_response import GetAccountBalancesResponse
from .types.get_account_usage_request_product import GetAccountUsageRequestProduct
from .types.get_account_usage_request_proxy_type import GetAccountUsageRequestProxyType
from .types.get_account_usage_response import GetAccountUsageResponse
from pydantic import ValidationError


class RawAccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_account_balances(
        self,
        *,
        product: typing.Optional[GetAccountBalancesRequestProduct] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetAccountBalancesResponse]:
        """
        Returns account-level balance summaries across available products. Use product-scoped balance endpoints when a page only needs one product.

        Parameters
        ----------
        product : typing.Optional[GetAccountBalancesRequestProduct]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetAccountBalancesResponse]
            Account balance summaries.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/account/balances",
            method="GET",
            params={
                "product": product,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetAccountBalancesResponse,
                    parse_obj_as(
                        type_=GetAccountBalancesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_account_usage(
        self,
        *,
        product: typing.Optional[GetAccountUsageRequestProduct] = None,
        from_: typing.Optional[GetAccountUsageRequestFromParams] = None,
        to: typing.Optional[GetAccountUsageRequestToParams] = None,
        subuser_id: typing.Optional[int] = None,
        proxy_type: typing.Optional[GetAccountUsageRequestProxyType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetAccountUsageResponse]:
        """
        Returns account-level usage across products with usage reporting as UTC period rollups. If from or to is supplied, product usage also includes requestedRange. Use subuserId from /v2/proxy/rotating/subusers to narrow rotating proxy usage; it does not apply to Web Data. Rotating proxy rollups report total traffic with txBytes and rxBytes set to null. Static proxies are inventory-only and are not included in usage responses.

        Parameters
        ----------
        product : typing.Optional[GetAccountUsageRequestProduct]

        from_ : typing.Optional[GetAccountUsageRequestFromParams]
            Date or datetime in RFC 3339 format

        to : typing.Optional[GetAccountUsageRequestToParams]
            Date or datetime in RFC 3339 format

        subuser_id : typing.Optional[int]
            Rotating proxy subuser ID from GET /v2/proxy/rotating/subusers. Omit to include all account subusers.

        proxy_type : typing.Optional[GetAccountUsageRequestProxyType]
            Rotating proxy type. Applies to rotating proxy usage.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetAccountUsageResponse]
            Account usage across available products.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/account/usage",
            method="GET",
            params={
                "product": product,
                "from": convert_and_respect_annotation_metadata(
                    object_=convert_and_respect_annotation_metadata(
                        object_=from_, annotation=GetAccountUsageRequestFromParams, direction="write"
                    ),
                    annotation=GetAccountUsageRequestFromParams,
                    direction="write",
                ),
                "to": convert_and_respect_annotation_metadata(
                    object_=convert_and_respect_annotation_metadata(
                        object_=to, annotation=GetAccountUsageRequestToParams, direction="write"
                    ),
                    annotation=GetAccountUsageRequestToParams,
                    direction="write",
                ),
                "subuserId": subuser_id,
                "proxyType": proxy_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetAccountUsageResponse,
                    parse_obj_as(
                        type_=GetAccountUsageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_account_balances(
        self,
        *,
        product: typing.Optional[GetAccountBalancesRequestProduct] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetAccountBalancesResponse]:
        """
        Returns account-level balance summaries across available products. Use product-scoped balance endpoints when a page only needs one product.

        Parameters
        ----------
        product : typing.Optional[GetAccountBalancesRequestProduct]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetAccountBalancesResponse]
            Account balance summaries.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/account/balances",
            method="GET",
            params={
                "product": product,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetAccountBalancesResponse,
                    parse_obj_as(
                        type_=GetAccountBalancesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_account_usage(
        self,
        *,
        product: typing.Optional[GetAccountUsageRequestProduct] = None,
        from_: typing.Optional[GetAccountUsageRequestFromParams] = None,
        to: typing.Optional[GetAccountUsageRequestToParams] = None,
        subuser_id: typing.Optional[int] = None,
        proxy_type: typing.Optional[GetAccountUsageRequestProxyType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetAccountUsageResponse]:
        """
        Returns account-level usage across products with usage reporting as UTC period rollups. If from or to is supplied, product usage also includes requestedRange. Use subuserId from /v2/proxy/rotating/subusers to narrow rotating proxy usage; it does not apply to Web Data. Rotating proxy rollups report total traffic with txBytes and rxBytes set to null. Static proxies are inventory-only and are not included in usage responses.

        Parameters
        ----------
        product : typing.Optional[GetAccountUsageRequestProduct]

        from_ : typing.Optional[GetAccountUsageRequestFromParams]
            Date or datetime in RFC 3339 format

        to : typing.Optional[GetAccountUsageRequestToParams]
            Date or datetime in RFC 3339 format

        subuser_id : typing.Optional[int]
            Rotating proxy subuser ID from GET /v2/proxy/rotating/subusers. Omit to include all account subusers.

        proxy_type : typing.Optional[GetAccountUsageRequestProxyType]
            Rotating proxy type. Applies to rotating proxy usage.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetAccountUsageResponse]
            Account usage across available products.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/account/usage",
            method="GET",
            params={
                "product": product,
                "from": convert_and_respect_annotation_metadata(
                    object_=convert_and_respect_annotation_metadata(
                        object_=from_, annotation=GetAccountUsageRequestFromParams, direction="write"
                    ),
                    annotation=GetAccountUsageRequestFromParams,
                    direction="write",
                ),
                "to": convert_and_respect_annotation_metadata(
                    object_=convert_and_respect_annotation_metadata(
                        object_=to, annotation=GetAccountUsageRequestToParams, direction="write"
                    ),
                    annotation=GetAccountUsageRequestToParams,
                    direction="write",
                ),
                "subuserId": subuser_id,
                "proxyType": proxy_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetAccountUsageResponse,
                    parse_obj_as(
                        type_=GetAccountUsageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorBody,
                        parse_obj_as(
                            type_=ApiErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
