# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ApiErrorBodyErrorDetails(UniversalBaseModel):
    target: typing.Optional[str] = None
    recovery_hint: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="recoveryHint"), pydantic.Field(alias="recoveryHint")
    ] = None
    active_session_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="activeSessionId"), pydantic.Field(alias="activeSessionId")
    ] = None
    next_operation_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="nextOperationId"), pydantic.Field(alias="nextOperationId")
    ] = None
    request_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="requestId"), pydantic.Field(alias="requestId")
    ] = None
    service_status: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="serviceStatus"), pydantic.Field(alias="serviceStatus")
    ] = None
    failure_stage: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="failureStage"), pydantic.Field(alias="failureStage")
    ] = None
    diagnostic_code: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="diagnosticCode"), pydantic.Field(alias="diagnosticCode")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
