# This file was auto-generated by Fern from our API Definition.

import typing

ApiErrorCode = typing.Union[
    typing.Literal[
        "unauthorized",
        "forbidden",
        "invalid_request",
        "insufficient_balance",
        "account_not_configured",
        "not_found",
        "settings_in_use",
        "settings_limit_reached",
        "session_limit_reached",
        "session_not_active",
        "session_active",
        "connection_in_use",
        "service_error",
        "internal_error",
    ],
    typing.Any,
]
