# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .browser_session_runtime import BrowserSessionRuntime
from .browser_session_settings import BrowserSessionSettings
from .browser_session_status import BrowserSessionStatus


class BrowserSession(UniversalBaseModel):
    id: str
    status: BrowserSessionStatus
    connect_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="connectUrl"), pydantic.Field(alias="connectUrl")
    ] = None
    settings: BrowserSessionSettings
    runtime: BrowserSessionRuntime
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]
    started_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="startedAt"), pydantic.Field(alias="startedAt")
    ] = None
    expires_at: typing_extensions.Annotated[str, FieldMetadata(alias="expiresAt"), pydantic.Field(alias="expiresAt")]
    ended_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="endedAt"), pydantic.Field(alias="endedAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
