# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .browser_session_settings_persistence import BrowserSessionSettingsPersistence


class BrowserSessionSettings(UniversalBaseModel):
    id: str
    persistence: BrowserSessionSettingsPersistence
    ttl_seconds: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="ttlSeconds"), pydantic.Field(alias="ttlSeconds")
    ] = None
    retention_expires_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="retentionExpiresAt"), pydantic.Field(alias="retentionExpiresAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
