# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RotatingProxyRequestEvent(UniversalBaseModel):
    date: str = pydantic.Field()
    """
    Event time, RFC3339, UTC.
    """

    host: str = pydantic.Field()
    """
    Target host the request went to (may include port for CONNECT/SOCKS5).
    """

    traffic_in: typing_extensions.Annotated[
        int, FieldMetadata(alias="trafficIn"), pydantic.Field(alias="trafficIn", description="Bytes received.")
    ]
    """
    Bytes received.
    """

    traffic_out: typing_extensions.Annotated[
        int, FieldMetadata(alias="trafficOut"), pydantic.Field(alias="trafficOut", description="Bytes sent.")
    ]
    """
    Bytes sent.
    """

    connect_duration_ms: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="connectDurationMs"),
        pydantic.Field(alias="connectDurationMs", description="Time to connect to the target host, milliseconds."),
    ]
    """
    Time to connect to the target host, milliseconds.
    """

    full_duration_ms: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="fullDurationMs"),
        pydantic.Field(alias="fullDurationMs", description="Total request duration, milliseconds."),
    ]
    """
    Total request duration, milliseconds.
    """

    subuser_id: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="subuserId"),
        pydantic.Field(alias="subuserId", description="Subuser the request went through. 0 if not applicable."),
    ]
    """
    Subuser the request went through. 0 if not applicable.
    """

    proxy_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="proxyType"),
        pydantic.Field(alias="proxyType", description='"residential", "mobile", or "datacenter".'),
    ]
    """
    "residential", "mobile", or "datacenter".
    """

    protocol: str = pydantic.Field()
    """
    Client-facing protocol, e.g. "http", "socks5".
    """

    country: str = pydantic.Field()
    """
    Requested proxy geo-targeting country. May be empty.
    """

    region: str = pydantic.Field()
    """
    Requested region. May be empty.
    """

    city: str = pydantic.Field()
    """
    Requested city. May be empty.
    """

    rotation: int = pydantic.Field()
    """
    Rotation setting used for the request.
    """

    session_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="sessionId"),
        pydantic.Field(alias="sessionId", description="Sticky-session ID if one was used. Omitted when empty."),
    ] = None
    """
    Sticky-session ID if one was used. Omitted when empty.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
