# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RotatingProxyTrafficUsageLast30Days(UniversalBaseModel):
    total_bytes: typing_extensions.Annotated[int, FieldMetadata(alias="totalBytes"), pydantic.Field(alias="totalBytes")]
    total_gb: typing_extensions.Annotated[float, FieldMetadata(alias="totalGb"), pydantic.Field(alias="totalGb")]
    tx_bytes: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="txBytes"),
        pydantic.Field(
            alias="txBytes", description="Upload bytes. Always null: usage is reported as total traffic only."
        ),
    ] = None
    """
    Upload bytes. Always null: usage is reported as total traffic only.
    """

    rx_bytes: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="rxBytes"),
        pydantic.Field(
            alias="rxBytes", description="Download bytes. Always null: usage is reported as total traffic only."
        ),
    ] = None
    """
    Download bytes. Always null: usage is reported as total traffic only.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
