# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rotating_proxy_balance_expiring import RotatingProxyBalanceExpiring
from .rotating_proxy_balance_non_expiring import RotatingProxyBalanceNonExpiring
from .rotating_proxy_balance_total import RotatingProxyBalanceTotal


class RotatingProxyBalance(UniversalBaseModel):
    expiring: RotatingProxyBalanceExpiring
    non_expiring: typing_extensions.Annotated[
        RotatingProxyBalanceNonExpiring, FieldMetadata(alias="nonExpiring"), pydantic.Field(alias="nonExpiring")
    ]
    total: RotatingProxyBalanceTotal

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
