# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .static_proxy_connection import StaticProxyConnection
from .static_proxy_proxy_type import StaticProxyProxyType


class StaticProxy(UniversalBaseModel):
    id: int
    ip: str
    proxy_type: typing_extensions.Annotated[
        StaticProxyProxyType, FieldMetadata(alias="proxyType"), pydantic.Field(alias="proxyType")
    ]
    country_code: typing_extensions.Annotated[
        str, FieldMetadata(alias="countryCode"), pydantic.Field(alias="countryCode")
    ]
    country_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="countryName"), pydantic.Field(alias="countryName")
    ]
    connection: StaticProxyConnection
    owned_from: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="ownedFrom"), pydantic.Field(alias="ownedFrom")
    ] = None
    owned_until: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="ownedUntil"), pydantic.Field(alias="ownedUntil")
    ] = None
    last_swap_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lastSwapAt"), pydantic.Field(alias="lastSwapAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
