# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class StaticProxyConnection(UniversalBaseModel):
    host: str
    port: int
    username: str
    password: str
    connection_string: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="connectionString"),
        pydantic.Field(alias="connectionString", description="Canonical copy-paste static proxy URL."),
    ]
    """
    Canonical copy-paste static proxy URL.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
