# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .web_data_request_usage_last7days import WebDataRequestUsageLast7Days
from .web_data_request_usage_last30days import WebDataRequestUsageLast30Days
from .web_data_request_usage_requested_range import WebDataRequestUsageRequestedRange
from .web_data_request_usage_yesterday import WebDataRequestUsageYesterday


class WebDataRequestUsage(UniversalBaseModel):
    """
    UTC usage rollups. yesterday is the previous UTC calendar day; last7Days and last30Days are rolling windows ending at request time.
    """

    yesterday: WebDataRequestUsageYesterday
    last7days: typing_extensions.Annotated[
        WebDataRequestUsageLast7Days, FieldMetadata(alias="last7Days"), pydantic.Field(alias="last7Days")
    ]
    last30days: typing_extensions.Annotated[
        WebDataRequestUsageLast30Days, FieldMetadata(alias="last30Days"), pydantic.Field(alias="last30Days")
    ]
    requested_range: typing_extensions.Annotated[
        typing.Optional[WebDataRequestUsageRequestedRange],
        FieldMetadata(alias="requestedRange"),
        pydantic.Field(
            alias="requestedRange",
            description="Usage for the requested from/to range. Present only when from or to is supplied.",
        ),
    ] = None
    """
    Usage for the requested from/to range. Present only when from or to is supplied.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
