# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata
from ...requests.static_proxy import StaticProxyParams


class ListStaticProxiesResponseParams(typing_extensions.TypedDict):
    items: typing.Sequence[StaticProxyParams]
    pending_count: typing_extensions.Annotated[int, FieldMetadata(alias="pendingCount")]
