# This file was auto-generated by Fern from our API Definition.

import typing

from .check_proxy_request_connection_string import CheckProxyRequestConnectionString
from .check_proxy_request_host import CheckProxyRequestHost

CheckProxyRequest = typing.Union[CheckProxyRequestConnectionString, CheckProxyRequestHost]
