# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .check_proxy_request_host_protocol import CheckProxyRequestHostProtocol


class CheckProxyRequestHost(UniversalBaseModel):
    host: str
    port: int
    username: str = pydantic.Field()
    """
    Proxy username to check.
    """

    password: str = pydantic.Field()
    """
    Proxy password to check.
    """

    protocol: typing.Optional[CheckProxyRequestHostProtocol] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
