# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevicesMode = typing.Union[
    typing.Literal["auto", "mask", "disabled"], typing.Any
]
