# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_browser_session_request_browser_fingerprint_geolocation_mode import (
    CreateBrowserSessionRequestBrowserFingerprintGeolocationMode,
)


class CreateBrowserSessionRequestBrowserFingerprintGeolocation(UniversalBaseModel):
    mode: CreateBrowserSessionRequestBrowserFingerprintGeolocationMode
    latitude: typing.Optional[float] = None
    longitude: typing.Optional[float] = None
    accuracy: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
