# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_browser_session_request_browser_fingerprint_masking_fonts_mode import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingFontsMode,
)


class CreateBrowserSessionRequestBrowserFingerprintMaskingFonts(UniversalBaseModel):
    mode: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMaskingFontsMode] = None
    families: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
