# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_browser_session_request_storage_cookies_items_item import (
    CreateBrowserSessionRequestStorageCookiesItemsItem,
)
from .create_browser_session_request_storage_cookies_mode import CreateBrowserSessionRequestStorageCookiesMode


class CreateBrowserSessionRequestStorageCookies(UniversalBaseModel):
    mode: typing.Optional[CreateBrowserSessionRequestStorageCookiesMode] = None
    items: typing.List[CreateBrowserSessionRequestStorageCookiesItemsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
