# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .create_browser_session_request_proxy_asn_rotation_mode import CreateBrowserSessionRequestProxyAsnRotationMode


class CreateBrowserSessionRequestProxyAsnRotation(UniversalBaseModel):
    mode: typing.Optional[CreateBrowserSessionRequestProxyAsnRotationMode] = None
    interval_minutes: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="intervalMinutes"), pydantic.Field(alias="intervalMinutes")
    ] = None
    sticky_key: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="stickyKey"), pydantic.Field(alias="stickyKey")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
