# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .create_browser_session_request_browser_fingerprint_geolocation import (
    CreateBrowserSessionRequestBrowserFingerprintGeolocation,
)
from .create_browser_session_request_browser_fingerprint_hardware import (
    CreateBrowserSessionRequestBrowserFingerprintHardware,
)
from .create_browser_session_request_browser_fingerprint_masking import (
    CreateBrowserSessionRequestBrowserFingerprintMasking,
)
from .create_browser_session_request_browser_fingerprint_os import CreateBrowserSessionRequestBrowserFingerprintOs
from .create_browser_session_request_browser_fingerprint_screen import (
    CreateBrowserSessionRequestBrowserFingerprintScreen,
)
from .create_browser_session_request_browser_fingerprint_strategy import (
    CreateBrowserSessionRequestBrowserFingerprintStrategy,
)
from .create_browser_session_request_browser_fingerprint_timezone import (
    CreateBrowserSessionRequestBrowserFingerprintTimezone,
)


class CreateBrowserSessionRequestBrowserFingerprint(UniversalBaseModel):
    strategy: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintStrategy] = None
    os: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintOs] = None
    os_version: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="osVersion"), pydantic.Field(alias="osVersion")
    ] = None
    user_agent: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="userAgent"), pydantic.Field(alias="userAgent")
    ] = None
    screen: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintScreen] = None
    locale: typing.Optional[str] = None
    timezone: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintTimezone] = None
    geolocation: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintGeolocation] = None
    hardware: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintHardware] = None
    masking: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMasking] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
