# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestBrowserFingerprintMaskingWebglMode = typing.Union[
    typing.Literal["auto", "noise", "mask", "off"], typing.Any
]
