# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestProxyAsnType = typing.Union[
    typing.Literal["residential", "mobile", "datacenter"], typing.Any
]
