# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestBrowserFingerprintMaskingWebrtc = typing.Union[
    typing.Literal["auto", "proxy", "disabled"], typing.Any
]
