# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestBrowserFingerprintMaskingAudioContext = typing.Union[
    typing.Literal["auto", "noise", "off"], typing.Any
]
