# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestProxyAsnRotationMode = typing.Union[
    typing.Literal["sticky", "perRequest", "interval"], typing.Any
]
