# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .create_browser_session_request_browser_fingerprint_masking_audio_context import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingAudioContext,
)
from .create_browser_session_request_browser_fingerprint_masking_canvas import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingCanvas,
)
from .create_browser_session_request_browser_fingerprint_masking_client_rects import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingClientRects,
)
from .create_browser_session_request_browser_fingerprint_masking_fonts import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingFonts,
)
from .create_browser_session_request_browser_fingerprint_masking_media_devices import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevices,
)
from .create_browser_session_request_browser_fingerprint_masking_webgl import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingWebgl,
)
from .create_browser_session_request_browser_fingerprint_masking_webrtc import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingWebrtc,
)


class CreateBrowserSessionRequestBrowserFingerprintMasking(UniversalBaseModel):
    canvas: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMaskingCanvas] = None
    webgl: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMaskingWebgl] = None
    audio_context: typing_extensions.Annotated[
        typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMaskingAudioContext],
        FieldMetadata(alias="audioContext"),
        pydantic.Field(alias="audioContext"),
    ] = None
    client_rects: typing_extensions.Annotated[
        typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMaskingClientRects],
        FieldMetadata(alias="clientRects"),
        pydantic.Field(alias="clientRects"),
    ] = None
    webrtc: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMaskingWebrtc] = None
    media_devices: typing_extensions.Annotated[
        typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevices],
        FieldMetadata(alias="mediaDevices"),
        pydantic.Field(alias="mediaDevices"),
    ] = None
    fonts: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMaskingFonts] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
