# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestBrowserFingerprintOs = typing.Union[
    typing.Literal["linux", "windows", "macos", "android"], typing.Any
]
