# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class CreateBrowserSessionRequestBrowserFingerprintHardware(UniversalBaseModel):
    cpu_cores: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="cpuCores"), pydantic.Field(alias="cpuCores")
    ] = None
    memory_gb: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="memoryGb"), pydantic.Field(alias="memoryGb")
    ] = None
    max_touch_points: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="maxTouchPoints"), pydantic.Field(alias="maxTouchPoints")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
