# This file was auto-generated by Fern from our API Definition.

import typing

from .create_browser_session_request_browser_fingerprint_timezone_zero import (
    CreateBrowserSessionRequestBrowserFingerprintTimezoneZero,
)

CreateBrowserSessionRequestBrowserFingerprintTimezone = typing.Union[
    CreateBrowserSessionRequestBrowserFingerprintTimezoneZero, str
]
