# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestStorageCookiesItemsItemSameSite = typing.Union[
    typing.Literal["strict", "lax", "none"], typing.Any
]
