# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_browser_session_request_proxy_ip_type import CreateBrowserSessionRequestProxyIpType


class CreateBrowserSessionRequestProxyIp(UniversalBaseModel):
    type: CreateBrowserSessionRequestProxyIpType
    ip: str = pydantic.Field()
    """
    A static IP owned by the account (GET /v2/proxy/static).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
