# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestBrowserFingerprintMaskingFontsMode = typing.Union[
    typing.Literal["auto", "custom"], typing.Any
]
