# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .create_browser_session_request_browser_fingerprint_masking_media_devices_mode import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevicesMode,
)


class CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevices(UniversalBaseModel):
    mode: typing.Optional[CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevicesMode] = None
    video_inputs: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="videoInputs"), pydantic.Field(alias="videoInputs")
    ] = None
    audio_inputs: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="audioInputs"), pydantic.Field(alias="audioInputs")
    ] = None
    audio_outputs: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="audioOutputs"), pydantic.Field(alias="audioOutputs")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
