# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .create_browser_session_request_storage_cookies_items_item_same_site import (
    CreateBrowserSessionRequestStorageCookiesItemsItemSameSite,
)


class CreateBrowserSessionRequestStorageCookiesItemsItem(UniversalBaseModel):
    name: str
    value: str
    url: typing.Optional[str] = None
    domain: typing.Optional[str] = None
    path: typing.Optional[str] = None
    expires: typing.Optional[int] = None
    http_only: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="httpOnly"), pydantic.Field(alias="httpOnly")
    ] = None
    secure: typing.Optional[bool] = None
    same_site: typing_extensions.Annotated[
        typing.Optional[CreateBrowserSessionRequestStorageCookiesItemsItemSameSite],
        FieldMetadata(alias="sameSite"),
        pydantic.Field(alias="sameSite"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
