# This file was auto-generated by Fern from our API Definition.

import typing

CreateBrowserSessionRequestBrowserFingerprintGeolocationMode = typing.Union[
    typing.Literal["auto", "custom", "disabled"], typing.Any
]
