# This file was auto-generated by Fern from our API Definition.

import typing

ListBrowserSessionsRequestStatus = typing.Union[typing.Literal["running", "stopped", "timedOut", "failed"], typing.Any]
