# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.browser_session import BrowserSession
from .raw_client import AsyncRawCloudBrowserClient, RawCloudBrowserClient
from .requests.create_browser_session_request_browser import CreateBrowserSessionRequestBrowserParams
from .requests.create_browser_session_request_persist import CreateBrowserSessionRequestPersistParams
from .requests.create_browser_session_request_proxy import CreateBrowserSessionRequestProxyParams
from .requests.create_browser_session_request_runtime import CreateBrowserSessionRequestRuntimeParams
from .requests.create_browser_session_request_settings import CreateBrowserSessionRequestSettingsParams
from .requests.create_browser_session_request_storage import CreateBrowserSessionRequestStorageParams
from .types.create_browser_session_live_view_response import CreateBrowserSessionLiveViewResponse
from .types.list_browser_sessions_request_status import ListBrowserSessionsRequestStatus
from .types.list_browser_sessions_response import ListBrowserSessionsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CloudBrowserClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCloudBrowserClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCloudBrowserClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCloudBrowserClient
        """
        return self._raw_client

    def list_browser_sessions(
        self,
        *,
        status: typing.Optional[ListBrowserSessionsRequestStatus] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBrowserSessionsResponse:
        """
        Lists browser session history using cursor pagination.

        Parameters
        ----------
        status : typing.Optional[ListBrowserSessionsRequestStatus]

        cursor : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBrowserSessionsResponse
            Browser session history.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.cloud_browser.list_browser_sessions()
        """
        _response = self._raw_client.list_browser_sessions(
            status=status, cursor=cursor, limit=limit, request_options=request_options
        )
        return _response.data

    def create_browser_session(
        self,
        *,
        settings: typing.Optional[CreateBrowserSessionRequestSettingsParams] = OMIT,
        browser: typing.Optional[CreateBrowserSessionRequestBrowserParams] = OMIT,
        storage: typing.Optional[CreateBrowserSessionRequestStorageParams] = OMIT,
        proxy: typing.Optional[CreateBrowserSessionRequestProxyParams] = OMIT,
        persist: typing.Optional[CreateBrowserSessionRequestPersistParams] = OMIT,
        runtime: typing.Optional[CreateBrowserSessionRequestRuntimeParams] = OMIT,
        start_url: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BrowserSession:
        """
        Creates and starts a browser. The smallest request is {} and creates burner browser state that is cleaned up after the session ends. Add persist.ttlSeconds to keep settings.id reusable for a bounded retention window.

        Parameters
        ----------
        settings : typing.Optional[CreateBrowserSessionRequestSettingsParams]

        browser : typing.Optional[CreateBrowserSessionRequestBrowserParams]

        storage : typing.Optional[CreateBrowserSessionRequestStorageParams]

        proxy : typing.Optional[CreateBrowserSessionRequestProxyParams]

        persist : typing.Optional[CreateBrowserSessionRequestPersistParams]

        runtime : typing.Optional[CreateBrowserSessionRequestRuntimeParams]

        start_url : typing.Optional[str]
            URL the browser opens when newly created settings launch.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowserSession
            Browser session started.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.cloud_browser.create_browser_session()
        """
        _response = self._raw_client.create_browser_session(
            settings=settings,
            browser=browser,
            storage=storage,
            proxy=proxy,
            persist=persist,
            runtime=runtime,
            start_url=start_url,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def get_browser_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BrowserSession:
        """
        Returns current session state and a freshly signed connection URL while the session is active.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowserSession
            Browser session state.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.cloud_browser.get_browser_session(
            session_id="sessionId",
        )
        """
        _response = self._raw_client.get_browser_session(session_id, request_options=request_options)
        return _response.data

    def delete_browser_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Deletes an ended browser session from history. Persistent browser state is not deleted; burner state is cleaned up when the session ends.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.cloud_browser.delete_browser_session(
            session_id="sessionId",
        )
        """
        _response = self._raw_client.delete_browser_session(session_id, request_options=request_options)
        return _response.data

    def stop_browser_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BrowserSession:
        """
        Idempotently stops the browser and synchronizes its saved browser state.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowserSession
            Stopped browser session.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.cloud_browser.stop_browser_session(
            session_id="sessionId",
        )
        """
        _response = self._raw_client.stop_browser_session(session_id, request_options=request_options)
        return _response.data

    def create_browser_session_live_view(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateBrowserSessionLiveViewResponse:
        """
        Returns a fresh live-view URL. It is rejected while a CDP relay is connected.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateBrowserSessionLiveViewResponse
            Fresh live-view URL.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.cloud_browser.create_browser_session_live_view(
            session_id="sessionId",
        )
        """
        _response = self._raw_client.create_browser_session_live_view(session_id, request_options=request_options)
        return _response.data

    def delete_browser_settings(
        self, settings_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Permanently deletes inactive saved settings and browser state. It never silently stops an active session.

        Parameters
        ----------
        settings_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.cloud_browser.delete_browser_settings(
            settings_id="settingsId",
        )
        """
        _response = self._raw_client.delete_browser_settings(settings_id, request_options=request_options)
        return _response.data


class AsyncCloudBrowserClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCloudBrowserClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCloudBrowserClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCloudBrowserClient
        """
        return self._raw_client

    async def list_browser_sessions(
        self,
        *,
        status: typing.Optional[ListBrowserSessionsRequestStatus] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBrowserSessionsResponse:
        """
        Lists browser session history using cursor pagination.

        Parameters
        ----------
        status : typing.Optional[ListBrowserSessionsRequestStatus]

        cursor : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBrowserSessionsResponse
            Browser session history.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.cloud_browser.list_browser_sessions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_browser_sessions(
            status=status, cursor=cursor, limit=limit, request_options=request_options
        )
        return _response.data

    async def create_browser_session(
        self,
        *,
        settings: typing.Optional[CreateBrowserSessionRequestSettingsParams] = OMIT,
        browser: typing.Optional[CreateBrowserSessionRequestBrowserParams] = OMIT,
        storage: typing.Optional[CreateBrowserSessionRequestStorageParams] = OMIT,
        proxy: typing.Optional[CreateBrowserSessionRequestProxyParams] = OMIT,
        persist: typing.Optional[CreateBrowserSessionRequestPersistParams] = OMIT,
        runtime: typing.Optional[CreateBrowserSessionRequestRuntimeParams] = OMIT,
        start_url: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BrowserSession:
        """
        Creates and starts a browser. The smallest request is {} and creates burner browser state that is cleaned up after the session ends. Add persist.ttlSeconds to keep settings.id reusable for a bounded retention window.

        Parameters
        ----------
        settings : typing.Optional[CreateBrowserSessionRequestSettingsParams]

        browser : typing.Optional[CreateBrowserSessionRequestBrowserParams]

        storage : typing.Optional[CreateBrowserSessionRequestStorageParams]

        proxy : typing.Optional[CreateBrowserSessionRequestProxyParams]

        persist : typing.Optional[CreateBrowserSessionRequestPersistParams]

        runtime : typing.Optional[CreateBrowserSessionRequestRuntimeParams]

        start_url : typing.Optional[str]
            URL the browser opens when newly created settings launch.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowserSession
            Browser session started.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.cloud_browser.create_browser_session()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_browser_session(
            settings=settings,
            browser=browser,
            storage=storage,
            proxy=proxy,
            persist=persist,
            runtime=runtime,
            start_url=start_url,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def get_browser_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BrowserSession:
        """
        Returns current session state and a freshly signed connection URL while the session is active.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowserSession
            Browser session state.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.cloud_browser.get_browser_session(
                session_id="sessionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_browser_session(session_id, request_options=request_options)
        return _response.data

    async def delete_browser_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Deletes an ended browser session from history. Persistent browser state is not deleted; burner state is cleaned up when the session ends.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.cloud_browser.delete_browser_session(
                session_id="sessionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_browser_session(session_id, request_options=request_options)
        return _response.data

    async def stop_browser_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BrowserSession:
        """
        Idempotently stops the browser and synchronizes its saved browser state.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BrowserSession
            Stopped browser session.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.cloud_browser.stop_browser_session(
                session_id="sessionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop_browser_session(session_id, request_options=request_options)
        return _response.data

    async def create_browser_session_live_view(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateBrowserSessionLiveViewResponse:
        """
        Returns a fresh live-view URL. It is rejected while a CDP relay is connected.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateBrowserSessionLiveViewResponse
            Fresh live-view URL.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.cloud_browser.create_browser_session_live_view(
                session_id="sessionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_browser_session_live_view(session_id, request_options=request_options)
        return _response.data

    async def delete_browser_settings(
        self, settings_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Permanently deletes inactive saved settings and browser state. It never silently stops an active session.

        Parameters
        ----------
        settings_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.cloud_browser.delete_browser_settings(
                settings_id="settingsId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_browser_settings(settings_id, request_options=request_options)
        return _response.data
