# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawProxyClient, RawProxyClient
from .requests.check_proxy_request import CheckProxyRequestParams
from .types.check_proxy_response import CheckProxyResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProxyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProxyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProxyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProxyClient
        """
        return self._raw_client

    def check_proxy(
        self, *, request: CheckProxyRequestParams, request_options: typing.Optional[RequestOptions] = None
    ) -> CheckProxyResponse:
        """
        Checks one proxy connection and returns the detected exit IP and location. Provide either connectionString or structured proxy fields.

        Parameters
        ----------
        request : CheckProxyRequestParams

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckProxyResponse
            Proxy check result.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.proxy.check_proxy(
            request={
                "connection_string": "http://user-USERNAME-type-residential-country-US-rotation-15:PASSWORD@geo.g-w.info:10080"
            },
        )
        """
        _response = self._raw_client.check_proxy(request=request, request_options=request_options)
        return _response.data


class AsyncProxyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProxyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProxyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProxyClient
        """
        return self._raw_client

    async def check_proxy(
        self, *, request: CheckProxyRequestParams, request_options: typing.Optional[RequestOptions] = None
    ) -> CheckProxyResponse:
        """
        Checks one proxy connection and returns the detected exit IP and location. Provide either connectionString or structured proxy fields.

        Parameters
        ----------
        request : CheckProxyRequestParams

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckProxyResponse
            Proxy check result.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.proxy.check_proxy(
                request={
                    "connection_string": "http://user-USERNAME-type-residential-country-US-rotation-15:PASSWORD@geo.g-w.info:10080"
                },
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.check_proxy(request=request, request_options=request_options)
        return _response.data
