# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .build_rotating_proxy_connection_response_parameters_protocol import (
    BuildRotatingProxyConnectionResponseParametersProtocol,
)
from .build_rotating_proxy_connection_response_parameters_type import BuildRotatingProxyConnectionResponseParametersType


class BuildRotatingProxyConnectionResponseParameters(UniversalBaseModel):
    subuser_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="subuserId"),
        pydantic.Field(
            alias="subuserId",
            description="Subuser ID from GET /v2/proxy/rotating/subusers. When omitted, the first account subuser is used.",
        ),
    ] = None
    """
    Subuser ID from GET /v2/proxy/rotating/subusers. When omitted, the first account subuser is used.
    """

    type: BuildRotatingProxyConnectionResponseParametersType = pydantic.Field()
    """
    Proxy type
    """

    country: str = pydantic.Field()
    """
    2-letter country code.
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    City name from GET /v2/proxy/rotating/locations. Spaces are encoded as underscores. Used only when state is not supplied.
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    State or subdivision value from GET /v2/proxy/rotating/locations. When supplied, it takes precedence over city.
    """

    asn: typing.Optional[str] = pydantic.Field(default=None)
    """
    Target ASN as digits.
    """

    rotation: typing.Optional[float] = pydantic.Field(default=None)
    """
    Rotation value: -1 for each request, 0 for sticky, or interval minutes.
    """

    session: typing.Optional[str] = None
    protocol: typing.Optional[BuildRotatingProxyConnectionResponseParametersProtocol] = None
    udp: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Route UDP traffic through the proxy. Supported only for SOCKS5 residential or mobile proxies.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
