# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.rotating_proxy_connection import RotatingProxyConnection
from .build_rotating_proxy_connection_response_parameters import BuildRotatingProxyConnectionResponseParameters


class BuildRotatingProxyConnectionResponse(UniversalBaseModel):
    connection: RotatingProxyConnection
    parameters: BuildRotatingProxyConnectionResponseParameters

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
