# This file was auto-generated by Fern from our API Definition.

import typing

BuildRotatingProxyConnectionResponseParametersProtocol = typing.Union[
    typing.Literal["http", "https", "socks5"], typing.Any
]
