# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.rotating_proxy_request_event import RotatingProxyRequestEvent


class ListRotatingProxyRequestsResponse(UniversalBaseModel):
    events: typing.List[RotatingProxyRequestEvent] = pydantic.Field()
    """
    Per-request events, sorted by date descending (newest first).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
