# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_rotating_proxy_locations_response_items_item import ListRotatingProxyLocationsResponseItemsItem
from .list_rotating_proxy_locations_response_type import ListRotatingProxyLocationsResponseType


class ListRotatingProxyLocationsResponse(UniversalBaseModel):
    type: ListRotatingProxyLocationsResponseType = pydantic.Field()
    """
    Proxy type
    """

    items: typing.List[ListRotatingProxyLocationsResponseItemsItem] = pydantic.Field()
    """
    Static country-level city and subdivision lists. When building a connection, state wins over city if both are supplied.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
