# This file was auto-generated by Fern from our API Definition.

import typing

ListRotatingProxyLocationsRequestType = typing.Union[typing.Literal["residential", "mobile", "datacenter"], typing.Any]
