# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...requests.rotating_proxy_connection import RotatingProxyConnectionParams
from .build_rotating_proxy_connection_response_parameters import BuildRotatingProxyConnectionResponseParametersParams


class BuildRotatingProxyConnectionResponseParams(typing_extensions.TypedDict):
    connection: RotatingProxyConnectionParams
    parameters: BuildRotatingProxyConnectionResponseParametersParams
