# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata
from ..types.build_rotating_proxy_connection_response_parameters_protocol import (
    BuildRotatingProxyConnectionResponseParametersProtocol,
)
from ..types.build_rotating_proxy_connection_response_parameters_type import (
    BuildRotatingProxyConnectionResponseParametersType,
)


class BuildRotatingProxyConnectionResponseParametersParams(typing_extensions.TypedDict):
    subuser_id: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="subuserId")]]
    """
    Subuser ID from GET /v2/proxy/rotating/subusers. When omitted, the first account subuser is used.
    """

    type: BuildRotatingProxyConnectionResponseParametersType
    """
    Proxy type
    """

    country: str
    """
    2-letter country code.
    """

    city: typing_extensions.NotRequired[str]
    """
    City name from GET /v2/proxy/rotating/locations. Spaces are encoded as underscores. Used only when state is not supplied.
    """

    state: typing_extensions.NotRequired[str]
    """
    State or subdivision value from GET /v2/proxy/rotating/locations. When supplied, it takes precedence over city.
    """

    asn: typing_extensions.NotRequired[str]
    """
    Target ASN as digits.
    """

    rotation: typing_extensions.NotRequired[float]
    """
    Rotation value: -1 for each request, 0 for sticky, or interval minutes.
    """

    session: typing_extensions.NotRequired[str]
    protocol: typing_extensions.NotRequired[BuildRotatingProxyConnectionResponseParametersProtocol]
    udp: typing_extensions.NotRequired[bool]
    """
    Route UDP traffic through the proxy. Supported only for SOCKS5 residential or mobile proxies.
    """
