# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...requests.subuser import SubuserParams


class CreateRotatingProxySubuserResponseParams(typing_extensions.TypedDict):
    subuser: SubuserParams
