# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata
from ..types.get_rotating_proxy_usage_response_filters_proxy_type import GetRotatingProxyUsageResponseFiltersProxyType


class GetRotatingProxyUsageResponseFiltersParams(typing_extensions.TypedDict):
    from_: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="from")]]
    to: typing_extensions.NotRequired[str]
    subuser_id: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="subuserId")]]
    proxy_type: typing_extensions.NotRequired[
        typing_extensions.Annotated[GetRotatingProxyUsageResponseFiltersProxyType, FieldMetadata(alias="proxyType")]
    ]
    """
    Proxy type
    """
