# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...requests.subuser import SubuserParams


class ListRotatingProxySubusersResponseParams(typing_extensions.TypedDict):
    items: typing.Sequence[SubuserParams]
