# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.list_rotating_proxy_locations_response_type import ListRotatingProxyLocationsResponseType
from .list_rotating_proxy_locations_response_items_item import ListRotatingProxyLocationsResponseItemsItemParams


class ListRotatingProxyLocationsResponseParams(typing_extensions.TypedDict):
    type: ListRotatingProxyLocationsResponseType
    """
    Proxy type
    """

    items: typing.Sequence[ListRotatingProxyLocationsResponseItemsItemParams]
    """
    Static country-level city and subdivision lists. When building a connection, state wins over city if both are supplied.
    """
