# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata


class ListRotatingProxyLocationsResponseItemsItemParams(typing_extensions.TypedDict):
    name: str
    country_code: typing_extensions.Annotated[str, FieldMetadata(alias="countryCode")]
    cities: typing.Sequence[str]
    states: typing.Sequence[str]
    """
    Static country-level state/subdivision values to send in POST /v2/proxy/rotating/connections. These are not city-under-state mappings.
    """
