# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...requests.rotating_proxy_request_event import RotatingProxyRequestEventParams


class ListRotatingProxyRequestsResponseParams(typing_extensions.TypedDict):
    events: typing.Sequence[RotatingProxyRequestEventParams]
    """
    Per-request events, sorted by date descending (newest first).
    """
