# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.api_error_code import ApiErrorCode
from .api_error_body_error_details import ApiErrorBodyErrorDetailsParams


class ApiErrorBodyErrorParams(typing_extensions.TypedDict):
    code: ApiErrorCode
    message: str
    details: ApiErrorBodyErrorDetailsParams
