# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata


class ApiErrorBodyErrorDetailsParams(typing_extensions.TypedDict):
    target: typing_extensions.NotRequired[str]
    recovery_hint: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="recoveryHint")]]
    active_session_id: typing_extensions.NotRequired[
        typing_extensions.Annotated[str, FieldMetadata(alias="activeSessionId")]
    ]
    next_operation_id: typing_extensions.NotRequired[
        typing_extensions.Annotated[str, FieldMetadata(alias="nextOperationId")]
    ]
    request_id: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="requestId")]]
    service_status: typing_extensions.NotRequired[
        typing_extensions.Annotated[int, FieldMetadata(alias="serviceStatus")]
    ]
    failure_stage: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="failureStage")]]
    diagnostic_code: typing_extensions.NotRequired[
        typing_extensions.Annotated[str, FieldMetadata(alias="diagnosticCode")]
    ]
