# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .api_error_body_error import ApiErrorBodyErrorParams


class ApiErrorBodyParams(typing_extensions.TypedDict):
    error: ApiErrorBodyErrorParams
