# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.browser_session_status import BrowserSessionStatus
from .browser_session_runtime import BrowserSessionRuntimeParams
from .browser_session_settings import BrowserSessionSettingsParams


class BrowserSessionParams(typing_extensions.TypedDict):
    id: str
    status: BrowserSessionStatus
    connect_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="connectUrl")]
    settings: BrowserSessionSettingsParams
    runtime: BrowserSessionRuntimeParams
    metadata: typing_extensions.NotRequired[typing.Dict[str, typing.Any]]
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt")]
    started_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="startedAt")]
    expires_at: typing_extensions.Annotated[str, FieldMetadata(alias="expiresAt")]
    ended_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="endedAt")]
