# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.browser_session_settings_persistence import BrowserSessionSettingsPersistence


class BrowserSessionSettingsParams(typing_extensions.TypedDict):
    id: str
    persistence: BrowserSessionSettingsPersistence
    ttl_seconds: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="ttlSeconds")]
    retention_expires_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="retentionExpiresAt")]
