# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata


class BrowserSessionRuntimeParams(typing_extensions.TypedDict):
    timeout_seconds: typing_extensions.NotRequired[
        typing_extensions.Annotated[int, FieldMetadata(alias="timeoutSeconds")]
    ]
    keep_alive: typing_extensions.NotRequired[typing_extensions.Annotated[bool, FieldMetadata(alias="keepAlive")]]
