# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.rotating_proxy_connection_protocol import RotatingProxyConnectionProtocol


class RotatingProxyConnectionParams(typing_extensions.TypedDict):
    """
    Generated proxy connection. Use connectionString as the primary copy-paste value.
    """

    protocol: RotatingProxyConnectionProtocol
    host: str
    port: int
    username: str
    password: str
    connection_string: typing_extensions.Annotated[str, FieldMetadata(alias="connectionString")]
    """
    Canonical copy-paste proxy URL.
    """
