# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .rotating_proxy_balance_total_traffic import RotatingProxyBalanceTotalTrafficParams


class RotatingProxyBalanceTotalParams(typing_extensions.TypedDict):
    traffic: RotatingProxyBalanceTotalTrafficParams
