# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata
from .rotating_proxy_balance_expiring import RotatingProxyBalanceExpiringParams
from .rotating_proxy_balance_non_expiring import RotatingProxyBalanceNonExpiringParams
from .rotating_proxy_balance_total import RotatingProxyBalanceTotalParams


class RotatingProxyBalanceParams(typing_extensions.TypedDict):
    expiring: RotatingProxyBalanceExpiringParams
    non_expiring: typing_extensions.Annotated[RotatingProxyBalanceNonExpiringParams, FieldMetadata(alias="nonExpiring")]
    total: RotatingProxyBalanceTotalParams
