# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata
from .rotating_proxy_traffic_usage_last7days import RotatingProxyTrafficUsageLast7DaysParams
from .rotating_proxy_traffic_usage_last30days import RotatingProxyTrafficUsageLast30DaysParams
from .rotating_proxy_traffic_usage_requested_range import RotatingProxyTrafficUsageRequestedRangeParams
from .rotating_proxy_traffic_usage_yesterday import RotatingProxyTrafficUsageYesterdayParams


class RotatingProxyTrafficUsageParams(typing_extensions.TypedDict):
    """
    UTC traffic rollups. yesterday is the previous UTC calendar day; last7Days and last30Days are rolling windows ending at request time.
    """

    yesterday: RotatingProxyTrafficUsageYesterdayParams
    last7days: typing_extensions.Annotated[RotatingProxyTrafficUsageLast7DaysParams, FieldMetadata(alias="last7Days")]
    last30days: typing_extensions.Annotated[
        RotatingProxyTrafficUsageLast30DaysParams, FieldMetadata(alias="last30Days")
    ]
    requested_range: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            RotatingProxyTrafficUsageRequestedRangeParams, FieldMetadata(alias="requestedRange")
        ]
    ]
    """
    Usage for the requested from/to range. Present only when from or to is supplied.
    """
