# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata


class RotatingProxyTrafficUsageLast30DaysParams(typing_extensions.TypedDict):
    total_bytes: typing_extensions.Annotated[int, FieldMetadata(alias="totalBytes")]
    total_gb: typing_extensions.Annotated[float, FieldMetadata(alias="totalGb")]
    tx_bytes: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="txBytes")]
    """
    Upload bytes. Always null: usage is reported as total traffic only.
    """

    rx_bytes: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="rxBytes")]
    """
    Download bytes. Always null: usage is reported as total traffic only.
    """
