# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .rotating_proxy_balance_non_expiring_traffic import RotatingProxyBalanceNonExpiringTrafficParams


class RotatingProxyBalanceNonExpiringParams(typing_extensions.TypedDict):
    traffic: RotatingProxyBalanceNonExpiringTrafficParams
