# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata


class RotatingProxyRequestEventParams(typing_extensions.TypedDict):
    date: str
    """
    Event time, RFC3339, UTC.
    """

    host: str
    """
    Target host the request went to (may include port for CONNECT/SOCKS5).
    """

    traffic_in: typing_extensions.Annotated[int, FieldMetadata(alias="trafficIn")]
    """
    Bytes received.
    """

    traffic_out: typing_extensions.Annotated[int, FieldMetadata(alias="trafficOut")]
    """
    Bytes sent.
    """

    connect_duration_ms: typing_extensions.Annotated[int, FieldMetadata(alias="connectDurationMs")]
    """
    Time to connect to the target host, milliseconds.
    """

    full_duration_ms: typing_extensions.Annotated[int, FieldMetadata(alias="fullDurationMs")]
    """
    Total request duration, milliseconds.
    """

    subuser_id: typing_extensions.Annotated[int, FieldMetadata(alias="subuserId")]
    """
    Subuser the request went through. 0 if not applicable.
    """

    proxy_type: typing_extensions.Annotated[str, FieldMetadata(alias="proxyType")]
    """
    "residential", "mobile", or "datacenter".
    """

    protocol: str
    """
    Client-facing protocol, e.g. "http", "socks5".
    """

    country: str
    """
    Requested proxy geo-targeting country. May be empty.
    """

    region: str
    """
    Requested region. May be empty.
    """

    city: str
    """
    Requested city. May be empty.
    """

    rotation: int
    """
    Rotation setting used for the request.
    """

    session_id: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="sessionId")]]
    """
    Sticky-session ID if one was used. Omitted when empty.
    """
