# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata


class RotatingProxyBalanceTotalTrafficParams(typing_extensions.TypedDict):
    available_bytes: typing_extensions.Annotated[int, FieldMetadata(alias="availableBytes")]
    available_gb: typing_extensions.Annotated[float, FieldMetadata(alias="availableGb")]
