# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata
from .rotating_proxy_balance_expiring_traffic import RotatingProxyBalanceExpiringTrafficParams


class RotatingProxyBalanceExpiringParams(typing_extensions.TypedDict):
    expires_at: typing_extensions.Annotated[str, FieldMetadata(alias="expiresAt")]
    traffic: RotatingProxyBalanceExpiringTrafficParams
