# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.static_proxy_proxy_type import StaticProxyProxyType
from .static_proxy_connection import StaticProxyConnectionParams


class StaticProxyParams(typing_extensions.TypedDict):
    id: int
    ip: str
    proxy_type: typing_extensions.Annotated[StaticProxyProxyType, FieldMetadata(alias="proxyType")]
    country_code: typing_extensions.Annotated[str, FieldMetadata(alias="countryCode")]
    country_name: typing_extensions.Annotated[str, FieldMetadata(alias="countryName")]
    connection: StaticProxyConnectionParams
    owned_from: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="ownedFrom")]
    owned_until: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="ownedUntil")]
    last_swap_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="lastSwapAt")]
