# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata


class StaticProxyConnectionParams(typing_extensions.TypedDict):
    host: str
    port: int
    username: str
    password: str
    connection_string: typing_extensions.Annotated[str, FieldMetadata(alias="connectionString")]
    """
    Canonical copy-paste static proxy URL.
    """
