# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class SubuserParams(typing_extensions.TypedDict):
    id: int
    name: str
    """
    Human-readable label for the proxy subuser.
    """

    username: str
    """
    Base proxy username. Prefix with user- when building smart proxy usernames.
    """

    password: str
