# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata
from .web_data_request_usage_last7days import WebDataRequestUsageLast7DaysParams
from .web_data_request_usage_last30days import WebDataRequestUsageLast30DaysParams
from .web_data_request_usage_requested_range import WebDataRequestUsageRequestedRangeParams
from .web_data_request_usage_yesterday import WebDataRequestUsageYesterdayParams


class WebDataRequestUsageParams(typing_extensions.TypedDict):
    """
    UTC usage rollups. yesterday is the previous UTC calendar day; last7Days and last30Days are rolling windows ending at request time.
    """

    yesterday: WebDataRequestUsageYesterdayParams
    last7days: typing_extensions.Annotated[WebDataRequestUsageLast7DaysParams, FieldMetadata(alias="last7Days")]
    last30days: typing_extensions.Annotated[WebDataRequestUsageLast30DaysParams, FieldMetadata(alias="last30Days")]
    requested_range: typing_extensions.NotRequired[
        typing_extensions.Annotated[WebDataRequestUsageRequestedRangeParams, FieldMetadata(alias="requestedRange")]
    ]
    """
    Usage for the requested from/to range. Present only when from or to is supplied.
    """
