# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class WebDataRequestUsageLast30DaysParams(typing_extensions.TypedDict):
    total: int
    successful: int
    failed: int
