# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .web_data_balance_requests import WebDataBalanceRequestsParams


class WebDataBalanceParams(typing_extensions.TypedDict):
    requests: WebDataBalanceRequestsParams
