# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class WebDataRequestUsageRequestedRangeParams(typing_extensions.TypedDict):
    """
    Usage for the requested from/to range. Present only when from or to is supplied.
    """

    total: int
    successful: int
    failed: int
