# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class WebDataBalanceRequestsParams(typing_extensions.TypedDict):
    total: int
    used: int
    remaining: int
