# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class FetchWebDataResponse(UniversalBaseModel):
    html: str = pydantic.Field()
    """
    HTML content returned by the target page.
    """

    source_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="sourceUrl"),
        pydantic.Field(alias="sourceUrl", description="Target URL that was fetched."),
    ]
    """
    Target URL that was fetched.
    """

    fetched_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="fetchedAt"),
        pydantic.Field(alias="fetchedAt", description="ISO 8601 timestamp when the fetch completed."),
    ]
    """
    ISO 8601 timestamp when the fetch completed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
