# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.web_data_search_result import WebDataSearchResult


class SearchWebDataResponse(UniversalBaseModel):
    request_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="requestId"),
        pydantic.Field(alias="requestId", description="Unique identifier for this search request."),
    ]
    """
    Unique identifier for this search request.
    """

    query: str = pydantic.Field()
    """
    Normalized search query.
    """

    results: typing.List[WebDataSearchResult] = pydantic.Field()
    """
    Organic results in search ranking order.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
