# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class CreateBrowserSessionRequestProxyAsnLocationParams(typing_extensions.TypedDict):
    country_code: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="countryCode")]]
    state: typing_extensions.NotRequired[str]
    city: typing_extensions.NotRequired[str]
