# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.create_browser_session_request_proxy_ip_type import CreateBrowserSessionRequestProxyIpType


class CreateBrowserSessionRequestProxyIpParams(typing_extensions.TypedDict):
    type: CreateBrowserSessionRequestProxyIpType
    ip: str
    """
    A static IP owned by the account (GET /v2/proxy/static).
    """
