# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.create_browser_session_request_browser_fingerprint_geolocation_mode import (
    CreateBrowserSessionRequestBrowserFingerprintGeolocationMode,
)


class CreateBrowserSessionRequestBrowserFingerprintGeolocationParams(typing_extensions.TypedDict):
    mode: CreateBrowserSessionRequestBrowserFingerprintGeolocationMode
    latitude: typing_extensions.NotRequired[float]
    longitude: typing_extensions.NotRequired[float]
    accuracy: typing_extensions.NotRequired[float]
