# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata
from ..types.create_browser_session_request_browser_fingerprint_masking_media_devices_mode import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevicesMode,
)


class CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevicesParams(typing_extensions.TypedDict):
    mode: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevicesMode]
    video_inputs: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="videoInputs")]]
    audio_inputs: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="audioInputs")]]
    audio_outputs: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="audioOutputs")]]
