# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata
from ..types.create_browser_session_request_browser_fingerprint_masking_audio_context import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingAudioContext,
)
from ..types.create_browser_session_request_browser_fingerprint_masking_canvas import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingCanvas,
)
from ..types.create_browser_session_request_browser_fingerprint_masking_client_rects import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingClientRects,
)
from ..types.create_browser_session_request_browser_fingerprint_masking_webrtc import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingWebrtc,
)
from .create_browser_session_request_browser_fingerprint_masking_fonts import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingFontsParams,
)
from .create_browser_session_request_browser_fingerprint_masking_media_devices import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevicesParams,
)
from .create_browser_session_request_browser_fingerprint_masking_webgl import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingWebglParams,
)


class CreateBrowserSessionRequestBrowserFingerprintMaskingParams(typing_extensions.TypedDict):
    canvas: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintMaskingCanvas]
    webgl: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintMaskingWebglParams]
    audio_context: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CreateBrowserSessionRequestBrowserFingerprintMaskingAudioContext, FieldMetadata(alias="audioContext")
        ]
    ]
    client_rects: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CreateBrowserSessionRequestBrowserFingerprintMaskingClientRects, FieldMetadata(alias="clientRects")
        ]
    ]
    webrtc: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintMaskingWebrtc]
    media_devices: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CreateBrowserSessionRequestBrowserFingerprintMaskingMediaDevicesParams, FieldMetadata(alias="mediaDevices")
        ]
    ]
    fonts: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintMaskingFontsParams]
