# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata
from ..types.create_browser_session_request_storage_cookies_items_item_same_site import (
    CreateBrowserSessionRequestStorageCookiesItemsItemSameSite,
)


class CreateBrowserSessionRequestStorageCookiesItemsItemParams(typing_extensions.TypedDict):
    name: str
    value: str
    url: typing_extensions.NotRequired[str]
    domain: typing_extensions.NotRequired[str]
    path: typing_extensions.NotRequired[str]
    expires: typing_extensions.NotRequired[int]
    http_only: typing_extensions.NotRequired[typing_extensions.Annotated[bool, FieldMetadata(alias="httpOnly")]]
    secure: typing_extensions.NotRequired[bool]
    same_site: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CreateBrowserSessionRequestStorageCookiesItemsItemSameSite, FieldMetadata(alias="sameSite")
        ]
    ]
