# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata
from ..types.create_browser_session_request_proxy_asn_rotation_mode import (
    CreateBrowserSessionRequestProxyAsnRotationMode,
)


class CreateBrowserSessionRequestProxyAsnRotationParams(typing_extensions.TypedDict):
    mode: typing_extensions.NotRequired[CreateBrowserSessionRequestProxyAsnRotationMode]
    interval_minutes: typing_extensions.NotRequired[
        typing_extensions.Annotated[float, FieldMetadata(alias="intervalMinutes")]
    ]
    sticky_key: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="stickyKey")]]
