# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.create_browser_session_request_browser_fingerprint_masking_fonts_mode import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingFontsMode,
)


class CreateBrowserSessionRequestBrowserFingerprintMaskingFontsParams(typing_extensions.TypedDict):
    mode: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintMaskingFontsMode]
    families: typing_extensions.NotRequired[typing.Sequence[str]]
