# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class CreateBrowserSessionRequestBrowserFingerprintHardwareParams(typing_extensions.TypedDict):
    cpu_cores: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="cpuCores")]]
    memory_gb: typing_extensions.NotRequired[typing_extensions.Annotated[int, FieldMetadata(alias="memoryGb")]]
    max_touch_points: typing_extensions.NotRequired[
        typing_extensions.Annotated[int, FieldMetadata(alias="maxTouchPoints")]
    ]
