# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .create_browser_session_request_storage_cookies import CreateBrowserSessionRequestStorageCookiesParams


class CreateBrowserSessionRequestStorageParams(typing_extensions.TypedDict):
    cookies: typing_extensions.NotRequired[CreateBrowserSessionRequestStorageCookiesParams]
