# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata
from ..types.create_browser_session_request_browser_fingerprint_os import (
    CreateBrowserSessionRequestBrowserFingerprintOs,
)
from ..types.create_browser_session_request_browser_fingerprint_strategy import (
    CreateBrowserSessionRequestBrowserFingerprintStrategy,
)
from .create_browser_session_request_browser_fingerprint_geolocation import (
    CreateBrowserSessionRequestBrowserFingerprintGeolocationParams,
)
from .create_browser_session_request_browser_fingerprint_hardware import (
    CreateBrowserSessionRequestBrowserFingerprintHardwareParams,
)
from .create_browser_session_request_browser_fingerprint_masking import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingParams,
)
from .create_browser_session_request_browser_fingerprint_screen import (
    CreateBrowserSessionRequestBrowserFingerprintScreenParams,
)
from .create_browser_session_request_browser_fingerprint_timezone import (
    CreateBrowserSessionRequestBrowserFingerprintTimezoneParams,
)


class CreateBrowserSessionRequestBrowserFingerprintParams(typing_extensions.TypedDict):
    strategy: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintStrategy]
    os: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintOs]
    os_version: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="osVersion")]]
    user_agent: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="userAgent")]]
    screen: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintScreenParams]
    locale: typing_extensions.NotRequired[str]
    timezone: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintTimezoneParams]
    geolocation: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintGeolocationParams]
    hardware: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintHardwareParams]
    masking: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintMaskingParams]
