# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.create_browser_session_request_proxy_asn_type import CreateBrowserSessionRequestProxyAsnType
from .create_browser_session_request_proxy_asn_location import CreateBrowserSessionRequestProxyAsnLocationParams
from .create_browser_session_request_proxy_asn_rotation import CreateBrowserSessionRequestProxyAsnRotationParams


class CreateBrowserSessionRequestProxyAsnParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[CreateBrowserSessionRequestProxyAsnType]
    location: typing_extensions.NotRequired[CreateBrowserSessionRequestProxyAsnLocationParams]
    asn: typing_extensions.NotRequired[str]
    rotation: typing_extensions.NotRequired[CreateBrowserSessionRequestProxyAsnRotationParams]
