# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class CreateBrowserSessionRequestPersistParams(typing_extensions.TypedDict):
    ttl_seconds: typing_extensions.Annotated[int, FieldMetadata(alias="ttlSeconds")]
