# This file was auto-generated by Fern from our API Definition.

import typing

from .create_browser_session_request_proxy_asn import CreateBrowserSessionRequestProxyAsnParams
from .create_browser_session_request_proxy_ip import CreateBrowserSessionRequestProxyIpParams

CreateBrowserSessionRequestProxyParams = typing.Union[
    CreateBrowserSessionRequestProxyIpParams, CreateBrowserSessionRequestProxyAsnParams
]
