# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class CreateBrowserSessionRequestBrowserFingerprintScreenParams(typing_extensions.TypedDict):
    width: int
    height: int
    device_pixel_ratio: typing_extensions.NotRequired[
        typing_extensions.Annotated[float, FieldMetadata(alias="devicePixelRatio")]
    ]
