# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.create_browser_session_request_storage_cookies_mode import CreateBrowserSessionRequestStorageCookiesMode
from .create_browser_session_request_storage_cookies_items_item import (
    CreateBrowserSessionRequestStorageCookiesItemsItemParams,
)


class CreateBrowserSessionRequestStorageCookiesParams(typing_extensions.TypedDict):
    mode: typing_extensions.NotRequired[CreateBrowserSessionRequestStorageCookiesMode]
    items: typing.Sequence[CreateBrowserSessionRequestStorageCookiesItemsItemParams]
