# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class CreateBrowserSessionLiveViewResponseParams(typing_extensions.TypedDict):
    live_view_url: typing_extensions.Annotated[str, FieldMetadata(alias="liveViewUrl")]
