# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.create_browser_session_request_browser_fingerprint_masking_webgl_mode import (
    CreateBrowserSessionRequestBrowserFingerprintMaskingWebglMode,
)


class CreateBrowserSessionRequestBrowserFingerprintMaskingWebglParams(typing_extensions.TypedDict):
    mode: typing_extensions.NotRequired[CreateBrowserSessionRequestBrowserFingerprintMaskingWebglMode]
    vendor: typing_extensions.NotRequired[str]
    renderer: typing_extensions.NotRequired[str]
