# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata
from ...requests.browser_session import BrowserSessionParams


class ListBrowserSessionsResponseParams(typing_extensions.TypedDict):
    items: typing.Sequence[BrowserSessionParams]
    next_cursor: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="nextCursor")]
