# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawStaticProxyClient, RawStaticProxyClient
from .types.list_static_proxies_response import ListStaticProxiesResponse


class StaticProxyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStaticProxyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStaticProxyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStaticProxyClient
        """
        return self._raw_client

    def list_static_proxies(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListStaticProxiesResponse:
        """
        Returns static proxy inventory for the authenticated account with a canonical connection.connectionString copy-paste URL. Static proxies are inventory-only in v2; usage reporting is not available for this product.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListStaticProxiesResponse
            Static proxy inventory.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.static_proxy.list_static_proxies()
        """
        _response = self._raw_client.list_static_proxies(request_options=request_options)
        return _response.data


class AsyncStaticProxyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStaticProxyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStaticProxyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStaticProxyClient
        """
        return self._raw_client

    async def list_static_proxies(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListStaticProxiesResponse:
        """
        Returns static proxy inventory for the authenticated account with a canonical connection.connectionString copy-paste URL. Static proxies are inventory-only in v2; usage reporting is not available for this product.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListStaticProxiesResponse
            Static proxy inventory.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.static_proxy.list_static_proxies()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_static_proxies(request_options=request_options)
        return _response.data
