# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..requests.get_rotating_proxy_usage_request_from import GetRotatingProxyUsageRequestFromParams
from ..requests.get_rotating_proxy_usage_request_to import GetRotatingProxyUsageRequestToParams
from ..requests.list_rotating_proxy_requests_request_from import ListRotatingProxyRequestsRequestFromParams
from ..requests.list_rotating_proxy_requests_request_to import ListRotatingProxyRequestsRequestToParams
from ..types.rotating_proxy_balance import RotatingProxyBalance
from .raw_client import AsyncRawRotatingProxyClient, RawRotatingProxyClient
from .types.build_rotating_proxy_connection_request_protocol import BuildRotatingProxyConnectionRequestProtocol
from .types.build_rotating_proxy_connection_request_type import BuildRotatingProxyConnectionRequestType
from .types.build_rotating_proxy_connection_response import BuildRotatingProxyConnectionResponse
from .types.create_rotating_proxy_subuser_response import CreateRotatingProxySubuserResponse
from .types.get_rotating_proxy_usage_request_proxy_type import GetRotatingProxyUsageRequestProxyType
from .types.get_rotating_proxy_usage_response import GetRotatingProxyUsageResponse
from .types.list_rotating_proxy_locations_request_type import ListRotatingProxyLocationsRequestType
from .types.list_rotating_proxy_locations_response import ListRotatingProxyLocationsResponse
from .types.list_rotating_proxy_requests_response import ListRotatingProxyRequestsResponse
from .types.list_rotating_proxy_subusers_response import ListRotatingProxySubusersResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RotatingProxyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRotatingProxyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRotatingProxyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRotatingProxyClient
        """
        return self._raw_client

    def build_rotating_proxy_connection(
        self,
        *,
        type: BuildRotatingProxyConnectionRequestType,
        country: str,
        subuser_id: typing.Optional[int] = OMIT,
        city: typing.Optional[str] = OMIT,
        state: typing.Optional[str] = OMIT,
        asn: typing.Optional[str] = OMIT,
        rotation: typing.Optional[float] = OMIT,
        session: typing.Optional[str] = OMIT,
        protocol: typing.Optional[BuildRotatingProxyConnectionRequestProtocol] = OMIT,
        udp: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BuildRotatingProxyConnectionResponse:
        """
        Builds one rotating proxy connection string from targeting and session options. Use connection.connectionString as the primary copy-paste value. Set subuserId to an ID from /v2/proxy/rotating/subusers, or omit it to use the first account subuser. Use locations first to choose valid country, city, and state values; state takes precedence over city.

        Parameters
        ----------
        type : BuildRotatingProxyConnectionRequestType
            Proxy type

        country : str
            2-letter country code.

        subuser_id : typing.Optional[int]
            Subuser ID from GET /v2/proxy/rotating/subusers. When omitted, the first account subuser is used.

        city : typing.Optional[str]
            City name from GET /v2/proxy/rotating/locations. Spaces are encoded as underscores. Used only when state is not supplied.

        state : typing.Optional[str]
            State or subdivision value from GET /v2/proxy/rotating/locations. When supplied, it takes precedence over city.

        asn : typing.Optional[str]
            Target ASN as digits.

        rotation : typing.Optional[float]
            Rotation value: -1 for each request, 0 for sticky, or interval minutes.

        session : typing.Optional[str]

        protocol : typing.Optional[BuildRotatingProxyConnectionRequestProtocol]

        udp : typing.Optional[bool]
            Route UDP traffic through the proxy. Supported only for SOCKS5 residential or mobile proxies.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BuildRotatingProxyConnectionResponse
            Generated rotating proxy connection details.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.rotating_proxy.build_rotating_proxy_connection(
            type="residential",
            country="US",
        )
        """
        _response = self._raw_client.build_rotating_proxy_connection(
            type=type,
            country=country,
            subuser_id=subuser_id,
            city=city,
            state=state,
            asn=asn,
            rotation=rotation,
            session=session,
            protocol=protocol,
            udp=udp,
            request_options=request_options,
        )
        return _response.data

    def list_rotating_proxy_subusers(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListRotatingProxySubusersResponse:
        """
        Returns rotating proxy subusers for the authenticated account. Use a subuser username and password when building proxy usernames manually. Pass a returned id as subuserId to /v2/proxy/rotating/connections, /v2/proxy/rotating/usage, or /v2/account/usage.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRotatingProxySubusersResponse
            Proxy subusers for the authenticated account.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.rotating_proxy.list_rotating_proxy_subusers()
        """
        _response = self._raw_client.list_rotating_proxy_subusers(request_options=request_options)
        return _response.data

    def create_rotating_proxy_subuser(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateRotatingProxySubuserResponse:
        """
        Creates a named rotating proxy subuser for the authenticated account and returns its proxy username and password. Use this when you need separate proxy identities for workloads, teams, or environments.

        Parameters
        ----------
        name : str
            Human-readable label for the new proxy subuser.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateRotatingProxySubuserResponse
            Proxy subuser created.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.rotating_proxy.create_rotating_proxy_subuser(
            name="crawler-prod",
        )
        """
        _response = self._raw_client.create_rotating_proxy_subuser(name=name, request_options=request_options)
        return _response.data

    def delete_rotating_proxy_subuser(
        self, subuser_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Deletes one proxy subuser owned by the authenticated account. Proxy strings that use the deleted username stop working. The final remaining subuser cannot be deleted.

        Parameters
        ----------
        subuser_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.rotating_proxy.delete_rotating_proxy_subuser(
            subuser_id=1,
        )
        """
        _response = self._raw_client.delete_rotating_proxy_subuser(subuser_id, request_options=request_options)
        return _response.data

    def list_rotating_proxy_locations(
        self, *, type: ListRotatingProxyLocationsRequestType, request_options: typing.Optional[RequestOptions] = None
    ) -> ListRotatingProxyLocationsResponse:
        """
        Returns supported rotating proxy countries with static country-level cities and state/subdivision lists. Cities are not nested under states. Use the returned city or state strings directly in buildRotatingProxyConnection; state takes precedence over city when both are supplied.

        Parameters
        ----------
        type : ListRotatingProxyLocationsRequestType
            Proxy type to list locations for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRotatingProxyLocationsResponse
            Available rotating proxy locations.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.rotating_proxy.list_rotating_proxy_locations(
            type="residential",
        )
        """
        _response = self._raw_client.list_rotating_proxy_locations(type=type, request_options=request_options)
        return _response.data

    def get_rotating_proxy_balance(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RotatingProxyBalance:
        """
        Returns rotating proxy traffic balance only. For account-level balances across products, use /v2/account/balances.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RotatingProxyBalance
            Rotating proxy traffic balance.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.rotating_proxy.get_rotating_proxy_balance()
        """
        _response = self._raw_client.get_rotating_proxy_balance(request_options=request_options)
        return _response.data

    def get_rotating_proxy_usage(
        self,
        *,
        from_: typing.Optional[GetRotatingProxyUsageRequestFromParams] = None,
        to: typing.Optional[GetRotatingProxyUsageRequestToParams] = None,
        subuser_id: typing.Optional[int] = None,
        proxy_type: typing.Optional[GetRotatingProxyUsageRequestProxyType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetRotatingProxyUsageResponse:
        """
        Returns rotating proxy traffic usage as UTC period rollups: yesterday, last7Days, and last30Days. If from or to is supplied, the response also includes requestedRange. Use subuserId from /v2/proxy/rotating/subusers to report one subuser, or omit it to include all account subusers. proxyType can be combined with subuserId. Rollups report total traffic with txBytes and rxBytes set to null.

        Parameters
        ----------
        from_ : typing.Optional[GetRotatingProxyUsageRequestFromParams]
            Date or datetime in RFC 3339 format

        to : typing.Optional[GetRotatingProxyUsageRequestToParams]
            Date or datetime in RFC 3339 format

        subuser_id : typing.Optional[int]
            Subuser ID from GET /v2/proxy/rotating/subusers. Omit to include all account subusers.

        proxy_type : typing.Optional[GetRotatingProxyUsageRequestProxyType]
            Proxy type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetRotatingProxyUsageResponse
            Rotating proxy traffic usage.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.rotating_proxy.get_rotating_proxy_usage(
            subuser_id=123,
        )
        """
        _response = self._raw_client.get_rotating_proxy_usage(
            from_=from_, to=to, subuser_id=subuser_id, proxy_type=proxy_type, request_options=request_options
        )
        return _response.data

    def list_rotating_proxy_requests(
        self,
        *,
        subuser_id: typing.Optional[int] = None,
        from_: typing.Optional[ListRotatingProxyRequestsRequestFromParams] = None,
        to: typing.Optional[ListRotatingProxyRequestsRequestToParams] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListRotatingProxyRequestsResponse:
        """
        Returns per-request analytics events for the authenticated account, one row per accessed host, sorted by date descending. Use subuserId from GET /v2/proxy/rotating/subusers to filter to one subuser, or omit it to include all account subusers. from and to must both be set or both omitted; the window defaults to the last 7 days when omitted. Page with limit/offset while keeping the window fixed.

        Parameters
        ----------
        subuser_id : typing.Optional[int]
            Subuser ID from GET /v2/proxy/rotating/subusers. Omit to include requests from all account subusers.

        from_ : typing.Optional[ListRotatingProxyRequestsRequestFromParams]
            Window start, RFC3339. from and to must both be set or both omitted. Defaults to the last 7 days when omitted.

        to : typing.Optional[ListRotatingProxyRequestsRequestToParams]
            Window end, RFC3339. Must be after from.

        limit : typing.Optional[int]
            Maximum events to return.

        offset : typing.Optional[int]
            Pagination offset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRotatingProxyRequestsResponse
            Rotating proxy request history.

        Examples
        --------
        from floppydata import FloppyData

        client = FloppyData(
            api_key="YOUR_API_KEY",
        )
        client.rotating_proxy.list_rotating_proxy_requests(
            subuser_id=123,
            limit=100,
            offset=0,
        )
        """
        _response = self._raw_client.list_rotating_proxy_requests(
            subuser_id=subuser_id, from_=from_, to=to, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data


class AsyncRotatingProxyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRotatingProxyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRotatingProxyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRotatingProxyClient
        """
        return self._raw_client

    async def build_rotating_proxy_connection(
        self,
        *,
        type: BuildRotatingProxyConnectionRequestType,
        country: str,
        subuser_id: typing.Optional[int] = OMIT,
        city: typing.Optional[str] = OMIT,
        state: typing.Optional[str] = OMIT,
        asn: typing.Optional[str] = OMIT,
        rotation: typing.Optional[float] = OMIT,
        session: typing.Optional[str] = OMIT,
        protocol: typing.Optional[BuildRotatingProxyConnectionRequestProtocol] = OMIT,
        udp: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BuildRotatingProxyConnectionResponse:
        """
        Builds one rotating proxy connection string from targeting and session options. Use connection.connectionString as the primary copy-paste value. Set subuserId to an ID from /v2/proxy/rotating/subusers, or omit it to use the first account subuser. Use locations first to choose valid country, city, and state values; state takes precedence over city.

        Parameters
        ----------
        type : BuildRotatingProxyConnectionRequestType
            Proxy type

        country : str
            2-letter country code.

        subuser_id : typing.Optional[int]
            Subuser ID from GET /v2/proxy/rotating/subusers. When omitted, the first account subuser is used.

        city : typing.Optional[str]
            City name from GET /v2/proxy/rotating/locations. Spaces are encoded as underscores. Used only when state is not supplied.

        state : typing.Optional[str]
            State or subdivision value from GET /v2/proxy/rotating/locations. When supplied, it takes precedence over city.

        asn : typing.Optional[str]
            Target ASN as digits.

        rotation : typing.Optional[float]
            Rotation value: -1 for each request, 0 for sticky, or interval minutes.

        session : typing.Optional[str]

        protocol : typing.Optional[BuildRotatingProxyConnectionRequestProtocol]

        udp : typing.Optional[bool]
            Route UDP traffic through the proxy. Supported only for SOCKS5 residential or mobile proxies.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BuildRotatingProxyConnectionResponse
            Generated rotating proxy connection details.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.rotating_proxy.build_rotating_proxy_connection(
                type="residential",
                country="US",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.build_rotating_proxy_connection(
            type=type,
            country=country,
            subuser_id=subuser_id,
            city=city,
            state=state,
            asn=asn,
            rotation=rotation,
            session=session,
            protocol=protocol,
            udp=udp,
            request_options=request_options,
        )
        return _response.data

    async def list_rotating_proxy_subusers(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListRotatingProxySubusersResponse:
        """
        Returns rotating proxy subusers for the authenticated account. Use a subuser username and password when building proxy usernames manually. Pass a returned id as subuserId to /v2/proxy/rotating/connections, /v2/proxy/rotating/usage, or /v2/account/usage.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRotatingProxySubusersResponse
            Proxy subusers for the authenticated account.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.rotating_proxy.list_rotating_proxy_subusers()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_rotating_proxy_subusers(request_options=request_options)
        return _response.data

    async def create_rotating_proxy_subuser(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateRotatingProxySubuserResponse:
        """
        Creates a named rotating proxy subuser for the authenticated account and returns its proxy username and password. Use this when you need separate proxy identities for workloads, teams, or environments.

        Parameters
        ----------
        name : str
            Human-readable label for the new proxy subuser.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateRotatingProxySubuserResponse
            Proxy subuser created.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.rotating_proxy.create_rotating_proxy_subuser(
                name="crawler-prod",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_rotating_proxy_subuser(name=name, request_options=request_options)
        return _response.data

    async def delete_rotating_proxy_subuser(
        self, subuser_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Deletes one proxy subuser owned by the authenticated account. Proxy strings that use the deleted username stop working. The final remaining subuser cannot be deleted.

        Parameters
        ----------
        subuser_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.rotating_proxy.delete_rotating_proxy_subuser(
                subuser_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_rotating_proxy_subuser(subuser_id, request_options=request_options)
        return _response.data

    async def list_rotating_proxy_locations(
        self, *, type: ListRotatingProxyLocationsRequestType, request_options: typing.Optional[RequestOptions] = None
    ) -> ListRotatingProxyLocationsResponse:
        """
        Returns supported rotating proxy countries with static country-level cities and state/subdivision lists. Cities are not nested under states. Use the returned city or state strings directly in buildRotatingProxyConnection; state takes precedence over city when both are supplied.

        Parameters
        ----------
        type : ListRotatingProxyLocationsRequestType
            Proxy type to list locations for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRotatingProxyLocationsResponse
            Available rotating proxy locations.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.rotating_proxy.list_rotating_proxy_locations(
                type="residential",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_rotating_proxy_locations(type=type, request_options=request_options)
        return _response.data

    async def get_rotating_proxy_balance(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RotatingProxyBalance:
        """
        Returns rotating proxy traffic balance only. For account-level balances across products, use /v2/account/balances.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RotatingProxyBalance
            Rotating proxy traffic balance.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.rotating_proxy.get_rotating_proxy_balance()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_rotating_proxy_balance(request_options=request_options)
        return _response.data

    async def get_rotating_proxy_usage(
        self,
        *,
        from_: typing.Optional[GetRotatingProxyUsageRequestFromParams] = None,
        to: typing.Optional[GetRotatingProxyUsageRequestToParams] = None,
        subuser_id: typing.Optional[int] = None,
        proxy_type: typing.Optional[GetRotatingProxyUsageRequestProxyType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetRotatingProxyUsageResponse:
        """
        Returns rotating proxy traffic usage as UTC period rollups: yesterday, last7Days, and last30Days. If from or to is supplied, the response also includes requestedRange. Use subuserId from /v2/proxy/rotating/subusers to report one subuser, or omit it to include all account subusers. proxyType can be combined with subuserId. Rollups report total traffic with txBytes and rxBytes set to null.

        Parameters
        ----------
        from_ : typing.Optional[GetRotatingProxyUsageRequestFromParams]
            Date or datetime in RFC 3339 format

        to : typing.Optional[GetRotatingProxyUsageRequestToParams]
            Date or datetime in RFC 3339 format

        subuser_id : typing.Optional[int]
            Subuser ID from GET /v2/proxy/rotating/subusers. Omit to include all account subusers.

        proxy_type : typing.Optional[GetRotatingProxyUsageRequestProxyType]
            Proxy type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetRotatingProxyUsageResponse
            Rotating proxy traffic usage.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.rotating_proxy.get_rotating_proxy_usage(
                subuser_id=123,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_rotating_proxy_usage(
            from_=from_, to=to, subuser_id=subuser_id, proxy_type=proxy_type, request_options=request_options
        )
        return _response.data

    async def list_rotating_proxy_requests(
        self,
        *,
        subuser_id: typing.Optional[int] = None,
        from_: typing.Optional[ListRotatingProxyRequestsRequestFromParams] = None,
        to: typing.Optional[ListRotatingProxyRequestsRequestToParams] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListRotatingProxyRequestsResponse:
        """
        Returns per-request analytics events for the authenticated account, one row per accessed host, sorted by date descending. Use subuserId from GET /v2/proxy/rotating/subusers to filter to one subuser, or omit it to include all account subusers. from and to must both be set or both omitted; the window defaults to the last 7 days when omitted. Page with limit/offset while keeping the window fixed.

        Parameters
        ----------
        subuser_id : typing.Optional[int]
            Subuser ID from GET /v2/proxy/rotating/subusers. Omit to include requests from all account subusers.

        from_ : typing.Optional[ListRotatingProxyRequestsRequestFromParams]
            Window start, RFC3339. from and to must both be set or both omitted. Defaults to the last 7 days when omitted.

        to : typing.Optional[ListRotatingProxyRequestsRequestToParams]
            Window end, RFC3339. Must be after from.

        limit : typing.Optional[int]
            Maximum events to return.

        offset : typing.Optional[int]
            Pagination offset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRotatingProxyRequestsResponse
            Rotating proxy request history.

        Examples
        --------
        import asyncio

        from floppydata import AsyncFloppyData

        client = AsyncFloppyData(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.rotating_proxy.list_rotating_proxy_requests(
                subuser_id=123,
                limit=100,
                offset=0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_rotating_proxy_requests(
            subuser_id=subuser_id, from_=from_, to=to, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data
